/*
 * Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
 * 
 * On Sat Aug 31 02:29:59 CST 2024
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTestDriver_h__
#define __mkTestDriver_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkMultiplier.h"


/* Class declaration for the mkTestDriver module */
class MOD_mkTestDriver : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_m_doneread;
  MOD_Reg<tUInt8> INST_m_doneread_double_write_error;
  MOD_Reg<tUInt32> INST_m_in;
  MOD_Reg<tUInt8> INST_m_in_double_write_error;
  MOD_Reg<tUInt8> INST_m_inited;
  MOD_Reg<tUInt8> INST_m_inited_double_write_error;
  MOD_Reg<tUInt32> INST_m_out;
  MOD_Reg<tUInt8> INST_m_out_double_write_error;
  MOD_Counter<tUInt32> INST_m_outstanding;
  MOD_Reg<tUInt8> INST_pipeline_chunker_index;
  MOD_Reg<tUInt8> INST_pipeline_chunker_index_double_write_error;
  MOD_Fifo<tUInt64> INST_pipeline_chunker_infifo;
  MOD_Fifo<tUWide> INST_pipeline_chunker_outfifo;
  MOD_Reg<tUWide> INST_pipeline_chunker_pending;
  MOD_Reg<tUInt8> INST_pipeline_chunker_pending_double_write_error;
  MOD_Fifo<tUWide> INST_pipeline_fft_fft_inputFIFO;
  MOD_Fifo<tUWide> INST_pipeline_fft_fft_outputFIFO;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_regValid_0;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_regValid_0_double_write_error;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_regValid_1;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_regValid_1_double_write_error;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_regValid_2;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_regValid_2_double_write_error;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_regValid_3;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_regValid_3_double_write_error;
  MOD_Reg<tUWide> INST_pipeline_fft_fft_regs_0;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_regs_0_double_write_error;
  MOD_Reg<tUWide> INST_pipeline_fft_fft_regs_1;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_regs_1_double_write_error;
  MOD_Reg<tUWide> INST_pipeline_fft_fft_regs_2;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_regs_2_double_write_error;
  MOD_Reg<tUWide> INST_pipeline_fft_fft_regs_3;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_regs_3_double_write_error;
  MOD_Fifo<tUInt32> INST_pipeline_fir_infifo;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_0;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_1;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_2;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_3;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_4;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_5;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_6;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_7;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_8;
  MOD_Fifo<tUInt32> INST_pipeline_fir_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_0;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_0_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_1;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_1_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_2;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_2_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_3;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_3_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_4;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_4_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_5;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_5_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_6;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_6_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_7;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_7_double_write_error;
  MOD_Fifo<tUWide> INST_pipeline_ifft_fft_fft_inputFIFO;
  MOD_Fifo<tUWide> INST_pipeline_ifft_fft_fft_outputFIFO;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_regValid_0;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_regValid_0_double_write_error;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_regValid_1;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_regValid_1_double_write_error;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_regValid_2;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_regValid_2_double_write_error;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_regValid_3;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_regValid_3_double_write_error;
  MOD_Reg<tUWide> INST_pipeline_ifft_fft_fft_regs_0;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_regs_0_double_write_error;
  MOD_Reg<tUWide> INST_pipeline_ifft_fft_fft_regs_1;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_regs_1_double_write_error;
  MOD_Reg<tUWide> INST_pipeline_ifft_fft_fft_regs_2;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_regs_2_double_write_error;
  MOD_Reg<tUWide> INST_pipeline_ifft_fft_fft_regs_3;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_regs_3_double_write_error;
  MOD_Fifo<tUWide> INST_pipeline_ifft_outfifo;
  MOD_Reg<tUInt8> INST_pipeline_splitter_index;
  MOD_Reg<tUInt8> INST_pipeline_splitter_index_double_write_error;
  MOD_Fifo<tUWide> INST_pipeline_splitter_infifo;
  MOD_Fifo<tUInt64> INST_pipeline_splitter_outfifo;
 
 /* Constructor */
 public:
  MOD_mkTestDriver(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_finish;
  tUInt8 DEF_CAN_FIRE_RL_finish;
  tUInt8 DEF_WILL_FIRE_RL_write;
  tUInt8 DEF_CAN_FIRE_RL_write;
  tUInt8 DEF_WILL_FIRE_RL_pad;
  tUInt8 DEF_CAN_FIRE_RL_pad;
  tUInt8 DEF_WILL_FIRE_RL_read;
  tUInt8 DEF_CAN_FIRE_RL_read;
  tUInt8 DEF_WILL_FIRE_RL_init;
  tUInt8 DEF_CAN_FIRE_RL_init;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_ifft_to_splitter;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_ifft_to_splitter;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fft_to_ifft;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fft_to_ifft;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_chunker_to_fft;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_chunker_to_fft;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fir_to_chunker;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fir_to_chunker;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_splitter_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_splitter_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_ifft_inversify;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_ifft_inversify;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_ifft_fft_fft_linear_fft;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_ifft_fft_fft_linear_fft;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fft_fft_linear_fft;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fft_fft_linear_fft;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_chunker_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_chunker_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fir_get_multiplier_res;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fir_get_multiplier_res;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fir_process;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fir_process;
  tUInt8 DEF_x__h7250;
  tUInt8 DEF_pipeline_ifft_fft_fft_regValid_3__h624970;
  tUInt8 DEF_pipeline_ifft_fft_fft_outputFIFO_notFull____d1272;
  tUInt8 DEF_pipeline_ifft_fft_fft_inputFIFO_notEmpty____d1278;
  tUInt8 DEF_pipeline_fft_fft_regValid_3__h317627;
  tUInt8 DEF_pipeline_fft_fft_outputFIFO_notFull____d127;
  tUInt8 DEF_pipeline_fft_fft_inputFIFO_notEmpty____d133;
  tUInt8 DEF_pipeline_chunker_index_2_EQ_7___d83;
  tUInt8 DEF_NOT_pipeline_ifft_fft_fft_inputFIFO_notEmpty__278___d1279;
  tUInt8 DEF_NOT_pipeline_fft_fft_inputFIFO_notEmpty__33___d134;
  tUInt8 DEF_NOT_pipeline_ifft_fft_fft_regValid_3_274___d1275;
  tUInt8 DEF_NOT_pipeline_fft_fft_regValid_3_29___d130;
 
 /* Local definitions */
 private:
  tUInt32 DEF_b__h638601;
  tUInt32 DEF_x__h638786;
  tUInt32 DEF_TASK_fopen___d2556;
  tUInt32 DEF_TASK_fopen___d2554;
  tUWide DEF_pipeline_splitter_infifo_first____d2459;
  tUWide DEF_pipeline_ifft_outfifo_first____d2545;
  tUWide DEF_pipeline_ifft_fft_fft_regs_3__h626149;
  tUWide DEF_pipeline_ifft_fft_fft_regs_2__h561438;
  tUWide DEF_pipeline_ifft_fft_fft_regs_1__h459093;
  tUWide DEF_pipeline_ifft_fft_fft_regs_0__h360603;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first____d2414;
  tUWide DEF_pipeline_ifft_fft_fft_inputFIFO_first____d1297;
  tUWide DEF_pipeline_fft_fft_regs_3__h318806;
  tUWide DEF_pipeline_fft_fft_regs_2__h253972;
  tUWide DEF_pipeline_fft_fft_regs_1__h151029;
  tUWide DEF_pipeline_fft_fft_regs_0__h51947;
  tUWide DEF_pipeline_fft_fft_outputFIFO_first____d2529;
  tUWide DEF_pipeline_fft_fft_inputFIFO_first____d152;
  tUWide DEF_pipeline_chunker_pending__h8174;
  tUWide DEF_pipeline_chunker_outfifo_first____d2513;
  tUInt32 DEF_m_out___d2585;
  tUWide DEF_pipeline_fft_fft_outputFIFO_first__529_BITS_51_ETC___d2541;
  tUWide DEF_pipeline_fft_fft_outputFIFO_first__529_BITS_51_ETC___d2538;
  tUWide DEF_pipeline_chunker_outfifo_first__513_BITS_511_T_ETC___d2525;
  tUWide DEF_pipeline_chunker_outfifo_first__513_BITS_511_T_ETC___d2522;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first__414_BI_ETC___d2453;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first__414_BI_ETC___d2443;
  tUWide DEF_pipeline_ifft_fft_fft_regs_2_990_BITS_447_TO_4_ETC___d2408;
  tUWide DEF_pipeline_ifft_fft_fft_regs_2_990_BITS_447_TO_4_ETC___d2402;
  tUWide DEF_pipeline_ifft_fft_fft_regs_1_643_BITS_447_TO_4_ETC___d1988;
  tUWide DEF_pipeline_ifft_fft_fft_regs_1_643_BITS_447_TO_4_ETC___d1982;
  tUWide DEF_pipeline_ifft_fft_fft_regs_0_298_BITS_447_TO_4_ETC___d1641;
  tUWide DEF_pipeline_ifft_fft_fft_regs_0_298_BITS_447_TO_4_ETC___d1635;
  tUWide DEF_pipeline_fft_fft_regs_2_45_BITS_447_TO_416_46__ETC___d1263;
  tUWide DEF_pipeline_fft_fft_regs_2_45_BITS_447_TO_416_46__ETC___d1257;
  tUWide DEF_pipeline_fft_fft_regs_1_98_BITS_447_TO_416_99__ETC___d843;
  tUWide DEF_pipeline_fft_fft_regs_1_98_BITS_447_TO_416_99__ETC___d837;
  tUWide DEF_IF_pipeline_chunker_index_2_EQ_7_3_THEN_pipeli_ETC___d119;
  tUWide DEF_IF_pipeline_chunker_index_2_EQ_7_3_THEN_pipeli_ETC___d112;
  tUWide DEF_pipeline_fft_fft_regs_0_53_BITS_447_TO_416_54__ETC___d496;
  tUWide DEF_pipeline_fft_fft_regs_0_53_BITS_447_TO_416_54__ETC___d490;
  tUWide DEF_pipeline_fft_fft_outputFIFO_first__529_BITS_51_ETC___d2535;
  tUWide DEF_pipeline_chunker_outfifo_first__513_BITS_511_T_ETC___d2519;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first__414_BI_ETC___d2433;
  tUWide DEF_pipeline_ifft_fft_fft_regs_2_990_BITS_447_TO_4_ETC___d2396;
  tUWide DEF_pipeline_ifft_fft_fft_regs_1_643_BITS_447_TO_4_ETC___d1976;
  tUWide DEF_pipeline_ifft_fft_fft_regs_0_298_BITS_447_TO_4_ETC___d1629;
  tUWide DEF_pipeline_fft_fft_regs_2_45_BITS_447_TO_416_46__ETC___d1251;
  tUWide DEF_pipeline_fft_fft_regs_1_98_BITS_447_TO_416_99__ETC___d831;
  tUWide DEF_IF_pipeline_chunker_index_2_EQ_7_3_THEN_pipeli_ETC___d105;
  tUWide DEF_pipeline_fft_fft_regs_0_53_BITS_447_TO_416_54__ETC___d484;
  tUWide DEF_pipeline_fft_fft_outputFIFO_first__529_BITS_51_ETC___d2532;
  tUWide DEF_pipeline_chunker_outfifo_first__513_BITS_511_T_ETC___d2516;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first__414_BI_ETC___d2423;
  tUWide DEF_pipeline_ifft_fft_fft_regs_2_990_BITS_447_TO_4_ETC___d2158;
  tUWide DEF_pipeline_ifft_fft_fft_regs_1_643_BITS_447_TO_4_ETC___d1810;
  tUWide DEF_pipeline_ifft_fft_fft_regs_0_298_BITS_447_TO_4_ETC___d1463;
  tUWide DEF_pipeline_fft_fft_regs_2_45_BITS_447_TO_416_46__ETC___d1013;
  tUWide DEF_pipeline_fft_fft_regs_1_98_BITS_447_TO_416_99__ETC___d665;
  tUWide DEF_IF_pipeline_chunker_index_2_EQ_7_3_THEN_pipeli_ETC___d98;
  tUWide DEF_pipeline_fft_fft_regs_0_53_BITS_447_TO_416_54__ETC___d318;
 
 /* Rules */
 public:
  void RL_pipeline_fir_process();
  void RL_pipeline_fir_get_multiplier_res();
  void RL_pipeline_chunker_iterate();
  void RL_pipeline_fft_fft_linear_fft();
  void RL_pipeline_ifft_fft_fft_linear_fft();
  void RL_pipeline_ifft_inversify();
  void RL_pipeline_splitter_iterate();
  void RL_pipeline_fir_to_chunker();
  void RL_pipeline_chunker_to_fft();
  void RL_pipeline_fft_to_ifft();
  void RL_pipeline_ifft_to_splitter();
  void RL_init();
  void RL_read();
  void RL_pad();
  void RL_write();
  void RL_finish();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTestDriver &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTestDriver &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTestDriver &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTestDriver &backing);
};

#endif /* ifndef __mkTestDriver_h__ */
