/*
 * Generated by Bluespec Compiler, version 2024.01-20-g9a97f9d0 (build 9a97f9d0)
 * 
 * On Thu Aug 15 20:41:06 CST 2024
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTbBypassFunctional_h__
#define __mkTbBypassFunctional_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTbBypassFunctional module */
class MOD_mkTbBypassFunctional : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_fifo_data_0;
  MOD_Reg<tUInt8> INST_fifo_data_1;
  MOD_Reg<tUInt8> INST_fifo_data_2;
  MOD_Reg<tUInt8> INST_fifo_deqP_ehrReg;
  MOD_Wire<tUInt8> INST_fifo_deqP_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo_deqP_ignored_wires_1;
  MOD_Wire<tUInt8> INST_fifo_deqP_ignored_wires_2;
  MOD_Reg<tUInt8> INST_fifo_deqP_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo_deqP_virtual_reg_1;
  MOD_Reg<tUInt8> INST_fifo_deqP_virtual_reg_2;
  MOD_Wire<tUInt8> INST_fifo_deqP_wires_0;
  MOD_Wire<tUInt8> INST_fifo_deqP_wires_1;
  MOD_Wire<tUInt8> INST_fifo_deqP_wires_2;
  MOD_Reg<tUInt8> INST_fifo_empty_ehrReg;
  MOD_Wire<tUInt8> INST_fifo_empty_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo_empty_ignored_wires_1;
  MOD_Wire<tUInt8> INST_fifo_empty_ignored_wires_2;
  MOD_Reg<tUInt8> INST_fifo_empty_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo_empty_virtual_reg_1;
  MOD_Reg<tUInt8> INST_fifo_empty_virtual_reg_2;
  MOD_Wire<tUInt8> INST_fifo_empty_wires_0;
  MOD_Wire<tUInt8> INST_fifo_empty_wires_1;
  MOD_Wire<tUInt8> INST_fifo_empty_wires_2;
  MOD_Reg<tUInt8> INST_fifo_enqP_ehrReg;
  MOD_Wire<tUInt8> INST_fifo_enqP_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo_enqP_ignored_wires_1;
  MOD_Wire<tUInt8> INST_fifo_enqP_ignored_wires_2;
  MOD_Reg<tUInt8> INST_fifo_enqP_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo_enqP_virtual_reg_1;
  MOD_Reg<tUInt8> INST_fifo_enqP_virtual_reg_2;
  MOD_Wire<tUInt8> INST_fifo_enqP_wires_0;
  MOD_Wire<tUInt8> INST_fifo_enqP_wires_1;
  MOD_Wire<tUInt8> INST_fifo_enqP_wires_2;
  MOD_Reg<tUInt8> INST_fifo_full_ehrReg;
  MOD_Wire<tUInt8> INST_fifo_full_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo_full_ignored_wires_1;
  MOD_Wire<tUInt8> INST_fifo_full_ignored_wires_2;
  MOD_Reg<tUInt8> INST_fifo_full_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo_full_virtual_reg_1;
  MOD_Reg<tUInt8> INST_fifo_full_virtual_reg_2;
  MOD_Wire<tUInt8> INST_fifo_full_wires_0;
  MOD_Wire<tUInt8> INST_fifo_full_wires_1;
  MOD_Wire<tUInt8> INST_fifo_full_wires_2;
  MOD_Reg<tUInt32> INST_m_cycle;
  MOD_Reg<tUInt32> INST_m_input_count;
  MOD_Reg<tUInt32> INST_m_output_count;
  MOD_Wire<tUInt8> INST_m_randomA_ignore;
  MOD_Reg<tUInt8> INST_m_randomA_initialized;
  MOD_Wire<tUInt8> INST_m_randomA_zaz;
  MOD_Wire<tUInt8> INST_m_randomB_ignore;
  MOD_Reg<tUInt8> INST_m_randomB_initialized;
  MOD_Wire<tUInt8> INST_m_randomB_zaz;
  MOD_Wire<tUInt8> INST_m_randomC_ignore;
  MOD_Reg<tUInt8> INST_m_randomC_initialized;
  MOD_Wire<tUInt8> INST_m_randomC_zaz;
  MOD_Wire<tUInt8> INST_m_randomData_ignore;
  MOD_Reg<tUInt8> INST_m_randomData_initialized;
  MOD_Wire<tUInt8> INST_m_randomData_zaz;
  MOD_Reg<tUInt8> INST_m_ref_fifo_elem_count_ehrReg;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_elem_count_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_ref_fifo_elem_count_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_elem_count_virtual_reg_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_wires_0;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_wires_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_elem_count_wires_2;
  MOD_Reg<tUInt32> INST_m_ref_fifo_enq_req_ehrReg;
  MOD_Wire<tUInt32> INST_m_ref_fifo_enq_req_ignored_wires_0;
  MOD_Wire<tUInt32> INST_m_ref_fifo_enq_req_ignored_wires_1;
  MOD_Wire<tUInt32> INST_m_ref_fifo_enq_req_ignored_wires_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_enq_req_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_ref_fifo_enq_req_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_enq_req_virtual_reg_2;
  MOD_Wire<tUInt32> INST_m_ref_fifo_enq_req_wires_0;
  MOD_Wire<tUInt32> INST_m_ref_fifo_enq_req_wires_1;
  MOD_Wire<tUInt32> INST_m_ref_fifo_enq_req_wires_2;
  MOD_Reg<tUInt32> INST_m_ref_fifo_fake_bypass_fifo_ehrReg;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ehrReg_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ehrReg_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ehrReg_3;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ehrReg_4;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_3;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_4;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_3;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_4;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_2_1;
  MOD_Fifo<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_0;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_0_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_0_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_0_3;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_0_4;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_1;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_3;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_2;
  MOD_Reg<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_2_1;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_bypass_fifo_wires_0;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_0_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_0_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_0_3;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_0_4;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_bypass_fifo_wires_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_1_1;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_1_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_1_3;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_1_4;
  MOD_Wire<tUInt32> INST_m_ref_fifo_fake_bypass_fifo_wires_2;
  MOD_Wire<tUInt8> INST_m_ref_fifo_fake_bypass_fifo_wires_2_1;
 
 /* Constructor */
 public:
  MOD_mkTbBypassFunctional(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_m_cycle_inc;
  tUInt8 DEF_CAN_FIRE_RL_m_cycle_inc;
  tUInt8 DEF_WILL_FIRE_RL_m_stop_tb;
  tUInt8 DEF_CAN_FIRE_RL_m_stop_tb;
  tUInt8 DEF_WILL_FIRE_RL_m_check_fifos_first;
  tUInt8 DEF_CAN_FIRE_RL_m_check_fifos_first;
  tUInt8 DEF_WILL_FIRE_RL_m_feed_inputs;
  tUInt8 DEF_WILL_FIRE_RL_m_check_fifos_not_empty;
  tUInt8 DEF_CAN_FIRE_RL_m_check_fifos_not_empty;
  tUInt8 DEF_WILL_FIRE_RL_m_check_fifos_not_full;
  tUInt8 DEF_CAN_FIRE_RL_m_check_fifos_not_full;
  tUInt8 DEF_WILL_FIRE_RL_m_maybe_clear;
  tUInt8 DEF_CAN_FIRE_RL_m_maybe_clear;
  tUInt8 DEF_WILL_FIRE_RL_m_check_outputs;
  tUInt8 DEF_CAN_FIRE_RL_m_check_outputs;
  tUInt8 DEF_CAN_FIRE_RL_m_feed_inputs;
  tUInt8 DEF_WILL_FIRE_RL_m_init;
  tUInt8 DEF_CAN_FIRE_RL_m_init;
  tUInt8 DEF_WILL_FIRE_RL_m_cycle_print;
  tUInt8 DEF_CAN_FIRE_RL_m_cycle_print;
  tUInt8 DEF_WILL_FIRE_RL_m_randomData_every_1;
  tUInt8 DEF_CAN_FIRE_RL_m_randomData_every_1;
  tUInt8 DEF_WILL_FIRE_RL_m_randomData_every;
  tUInt8 DEF_CAN_FIRE_RL_m_randomData_every;
  tUInt8 DEF_WILL_FIRE_RL_m_randomC_every_1;
  tUInt8 DEF_CAN_FIRE_RL_m_randomC_every_1;
  tUInt8 DEF_WILL_FIRE_RL_m_randomC_every;
  tUInt8 DEF_CAN_FIRE_RL_m_randomC_every;
  tUInt8 DEF_WILL_FIRE_RL_m_randomB_every_1;
  tUInt8 DEF_CAN_FIRE_RL_m_randomB_every_1;
  tUInt8 DEF_WILL_FIRE_RL_m_randomB_every;
  tUInt8 DEF_CAN_FIRE_RL_m_randomB_every;
  tUInt8 DEF_WILL_FIRE_RL_m_randomA_every_1;
  tUInt8 DEF_CAN_FIRE_RL_m_randomA_every_1;
  tUInt8 DEF_WILL_FIRE_RL_m_randomA_every;
  tUInt8 DEF_CAN_FIRE_RL_m_randomA_every;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_enq_req_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_enq_req_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_elem_count_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_elem_count_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_post_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_post_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_two;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_two;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_one;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_one;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_4;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_4;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_3;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_3;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_2;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_2;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_1;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_1;
  tUInt8 DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_fifo_full_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_full_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_fifo_empty_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_empty_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_fifo_deqP_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_deqP_canonicalize;
  tUInt8 DEF_WILL_FIRE_RL_fifo_enqP_canonicalize;
  tUInt8 DEF_CAN_FIRE_RL_fifo_enqP_canonicalize;
  tUInt8 DEF_fifo_empty_virtual_reg_2_read__58_OR_fifo_empt_ETC___d264;
  tUInt8 DEF_IF_fifo_empty_wires_0_whas__5_THEN_fifo_empty__ETC___d28;
  tUInt8 DEF_fifo_empty_virtual_reg_1_read____d259;
  tUInt8 DEF_fifo_empty_virtual_reg_2_read____d258;
  tUInt8 DEF_fifo_full_virtual_reg_2_read__13_OR_fifo_full__ETC___d219;
  tUInt8 DEF_fifo_full_ehrReg__h4601;
  tUInt8 DEF_fifo_full_virtual_reg_0_read____d215;
  tUInt8 DEF_fifo_full_virtual_reg_1_read____d214;
  tUInt8 DEF_fifo_full_virtual_reg_2_read____d213;
  tUInt8 DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_4_whas__ETC___d80;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_re_ETC___d269;
  tUInt8 DEF_m_ref_fifo_enq_req_virtual_reg_2_read____d147;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_read____d87;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_2_read____d86;
  tUInt32 DEF_x__h23804;
  tUInt32 DEF_x__h23951;
  tUInt32 DEF_m_ref_fifo_enq_req_wires_1_wget____d140;
  tUInt32 DEF_m_ref_fifo_enq_req_wires_0_wget____d142;
  tUInt32 DEF_m_ref_fifo_enq_req_ehrReg___d143;
  tUInt32 DEF_m_ref_fifo_fake_bypass_fifo_wires_0_wget____d46;
  tUInt32 DEF_m_ref_fifo_fake_bypass_fifo_ehrReg___d47;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_wget____d56;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_1___d57;
  tUInt8 DEF_x_wget__h12540;
  tUInt8 DEF_def__h23403;
  tUInt8 DEF_x_wget__h16362;
  tUInt8 DEF_x_wget__h15986;
  tUInt8 DEF_m_ref_fifo_enq_req_wires_1_whas____d139;
  tUInt8 DEF_m_ref_fifo_enq_req_wires_0_whas____d141;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_read____d265;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_wires_0_4_whas____d77;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_wires_0_4_wget____d78;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_4__h9787;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_3__h8958;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_2_1_read____d97;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_1_read____d98;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_whas____d55;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_wires_0_whas____d45;
  tUInt8 DEF_m_ref_fifo_elem_count_virtual_reg_2_read____d205;
  tUInt8 DEF_m_ref_fifo_elem_count_virtual_reg_1_read____d206;
  tUInt8 DEF_fifo_empty_wires_0_whas____d25;
  tUInt8 DEF_fifo_empty_wires_0_wget____d26;
  tUInt8 DEF_fifo_empty_ehrReg__h3485;
  tUInt8 DEF_m_ref_fifo_enq_req_ehrReg_43_BIT_8___d152;
  tUInt8 DEF_m_ref_fifo_enq_req_wires_0_wget__42_BIT_8___d150;
  tUInt8 DEF_m_ref_fifo_enq_req_wires_1_wget__40_BIT_8___d148;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_wires_0_wget__6_BIT_8___d88;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_7_BIT_8___d90;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_1_7_BIT_1___d101;
  tUInt8 DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_wget__6__ETC___d99;
  tUInt8 DEF_n__read__h21435;
  tUInt8 DEF_def__h13340;
  tUInt8 DEF_n__read__h19790;
  tUInt8 DEF_v__h16492;
  tUInt8 DEF_v__h16116;
  tUInt8 DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_3_whas__ETC___d73;
  tUInt8 DEF_m_input_count_24_EQ_1024___d333;
  tUInt8 DEF_IF_m_ref_fifo_elem_count_virtual_reg_2_read__0_ETC___d256;
  tUInt8 DEF_IF_m_randomB_zaz_whas__85_THEN_m_randomB_zaz_w_ETC___d253;
  tUInt8 DEF_IF_m_randomA_zaz_whas__78_THEN_m_randomA_zaz_w_ETC___d204;
  tUInt8 DEF_NOT_IF_m_ref_fifo_elem_count_virtual_reg_2_rea_ETC___d257;
  tUInt8 DEF_NOT_IF_m_ref_fifo_elem_count_virtual_reg_2_rea_ETC___d212;
  tUInt8 DEF_NOT_fifo_empty_virtual_reg_2_read__58_22_AND_N_ETC___d325;
 
 /* Local definitions */
 private:
  tUInt8 DEF_NOT_m_ref_fifo_fake_bypass_fifo_virtual_reg_1__ETC___d291;
  tUInt32 DEF_v__h17170;
  tUInt32 DEF_v__h16793;
  tUInt32 DEF_v__h16419;
  tUInt32 DEF_v__h16043;
  tUInt32 DEF_x__h22477;
  tUInt8 DEF_x_wget__h7546;
  tUInt8 DEF_def__h22235;
  tUInt8 DEF_x_wget__h17113;
  tUInt8 DEF__read__h226;
  tUInt8 DEF__read__h200;
  tUInt8 DEF__read__h174;
  tUInt8 DEF_x_wget__h16736;
  tUInt8 DEF_x_wget__h12589;
  tUInt8 DEF_x_wget__h1601;
  tUInt8 DEF_x_wget__h1552;
  tUInt8 DEF_def__h22669;
  tUInt8 DEF_x_wget__h501;
  tUInt8 DEF_x_wget__h452;
  tUInt8 DEF_def__h22845;
  tUInt8 DEF_fifo_deqP_virtual_reg_2_read____d242;
  tUInt8 DEF_fifo_deqP_virtual_reg_1_read____d243;
  tUInt8 DEF_fifo_enqP_virtual_reg_2_read____d227;
  tUInt8 DEF_fifo_enqP_virtual_reg_1_read____d228;
  tUInt8 DEF_x__h14652;
  tUInt8 DEF_x__h14653;
  tUInt8 DEF_x_first__h4684;
  tUInt8 DEF_n__read__h20754;
  tUInt32 DEF_IF_m_ref_fifo_enq_req_wires_1_whas__39_THEN_m__ETC___d145;
  tUInt32 DEF_IF_m_ref_fifo_enq_req_wires_0_whas__41_THEN_m__ETC___d144;
  tUInt32 DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_whas__5_ETC___d48;
  tUInt8 DEF_x_first__h12331;
  tUInt8 DEF_def__h8034;
  tUInt8 DEF_x_first__h15685;
  tUInt8 DEF_v__h17243;
  tUInt8 DEF_IF_m_ref_fifo_enq_req_wires_0_whas__41_THEN_IF_ETC___d171;
  tUInt8 DEF_v__h16866;
  tUInt8 DEF_def__h1255;
  tUInt8 DEF_def__h2352;
  tUInt8 DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_1_whas__ETC___d58;
  tUInt8 DEF_def__h13222;
  tUInt8 DEF_def__h2234;
  tUInt8 DEF_def__h1137;
  tUInt8 DEF_IF_fifo_full_wires_1_whas__3_THEN_fifo_full_wi_ETC___d39;
  tUInt8 DEF_IF_fifo_full_wires_0_whas__5_THEN_fifo_full_wi_ETC___d38;
  tUInt8 DEF_IF_fifo_empty_wires_1_whas__3_THEN_fifo_empty__ETC___d29;
  tUInt32 DEF__0_CONCAT_DONTCARE___d125;
 
 /* Rules */
 public:
  void RL_fifo_enqP_canonicalize();
  void RL_fifo_deqP_canonicalize();
  void RL_fifo_empty_canonicalize();
  void RL_fifo_full_canonicalize();
  void RL_m_ref_fifo_fake_bypass_fifo_canonicalize();
  void RL_m_ref_fifo_fake_bypass_fifo_canonicalize_1();
  void RL_m_ref_fifo_fake_bypass_fifo_canonicalize_2();
  void RL_m_ref_fifo_fake_bypass_fifo_canonicalize_3();
  void RL_m_ref_fifo_fake_bypass_fifo_canonicalize_4();
  void RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_one();
  void RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_two();
  void RL_m_ref_fifo_fake_bypass_fifo_post_canonicalize();
  void RL_m_ref_fifo_elem_count_canonicalize();
  void RL_m_ref_fifo_enq_req_canonicalize();
  void RL_m_ref_fifo_canonicalize();
  void RL_m_randomA_every();
  void RL_m_randomA_every_1();
  void RL_m_randomB_every();
  void RL_m_randomB_every_1();
  void RL_m_randomC_every();
  void RL_m_randomC_every_1();
  void RL_m_randomData_every();
  void RL_m_randomData_every_1();
  void RL_m_cycle_print();
  void RL_m_init();
  void RL_m_feed_inputs();
  void RL_m_check_outputs();
  void RL_m_maybe_clear();
  void RL_m_check_fifos_not_full();
  void RL_m_check_fifos_not_empty();
  void RL_m_check_fifos_first();
  void RL_m_stop_tb();
  void RL_m_cycle_inc();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbBypassFunctional &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTbBypassFunctional &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTbBypassFunctional &backing);
};

#endif /* ifndef __mkTbBypassFunctional_h__ */
