/*
 * Generated by Bluespec Compiler, version 2024.01-20-g9a97f9d0 (build 9a97f9d0)
 * 
 * On Fri Aug 16 18:13:35 CST 2024
 * 
 */

/* Generation options: keep-fires */
#ifndef __model_mkTbCFScheduling_h__
#define __model_mkTbCFScheduling_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkTbCFScheduling.h"

/* Class declaration for a model of mkTbCFScheduling */
class MODEL_mkTbCFScheduling : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkTbCFScheduling *mkTbCFScheduling_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkTbCFScheduling();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(char const **name, char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkTbCFScheduling();
}

#endif /* ifndef __model_mkTbCFScheduling_h__ */
