/*
 * Generated by Bluespec Compiler, version 2024.01-20-g9a97f9d0 (build 9a97f9d0)
 * 
 * On Thu Aug 15 20:41:06 CST 2024
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTbBypassFunctional.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTbBypassFunctional::MODEL_mkTbBypassFunctional()
{
  mkTbBypassFunctional_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTbBypassFunctional()
{
  MODEL_mkTbBypassFunctional *model = new MODEL_mkTbBypassFunctional();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTbBypassFunctional &INST_top = *((MOD_mkTbBypassFunctional *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_re_ETC___d270;
	 tUInt8 DEF_INST_top_DEF_m_randomA_initialized__h16110;
	 tUInt8 DEF_INST_top_DEF_m_randomB_initialized__h16486;
	 tUInt8 DEF_INST_top_DEF_m_randomData_initialized__h17237;
	 tUInt8 DEF_INST_top_DEF_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo_i_n_ETC___d84;
	 tUInt8 DEF_INST_top_DEF_m_randomC_initialized__h16860;
	 INST_top.DEF_CAN_FIRE_RL_fifo_deqP_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_fifo_deqP_canonicalize = INST_top.DEF_CAN_FIRE_RL_fifo_deqP_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_fifo_empty_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_fifo_empty_canonicalize = INST_top.DEF_CAN_FIRE_RL_fifo_empty_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_fifo_enqP_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_fifo_enqP_canonicalize = INST_top.DEF_CAN_FIRE_RL_fifo_enqP_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_fifo_full_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_fifo_full_canonicalize = INST_top.DEF_CAN_FIRE_RL_fifo_full_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_m_check_fifos_not_empty = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_check_fifos_not_empty = INST_top.DEF_CAN_FIRE_RL_m_check_fifos_not_empty;
	 INST_top.DEF_CAN_FIRE_RL_m_cycle_inc = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_cycle_inc = INST_top.DEF_CAN_FIRE_RL_m_cycle_inc;
	 INST_top.DEF_CAN_FIRE_RL_m_check_fifos_not_full = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_check_fifos_not_full = INST_top.DEF_CAN_FIRE_RL_m_check_fifos_not_full;
	 INST_top.DEF_CAN_FIRE_RL_m_cycle_print = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_cycle_print = INST_top.DEF_CAN_FIRE_RL_m_cycle_print;
	 INST_top.DEF_CAN_FIRE_RL_m_randomA_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_randomA_every = INST_top.DEF_CAN_FIRE_RL_m_randomA_every;
	 INST_top.DEF_x__h23951 = INST_top.INST_m_cycle.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_init = (INST_top.DEF_x__h23951) == 0u;
	 INST_top.DEF_WILL_FIRE_RL_m_init = INST_top.DEF_CAN_FIRE_RL_m_init;
	 DEF_INST_top_DEF_m_randomC_initialized__h16860 = INST_top.INST_m_randomC_initialized.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_maybe_clear = DEF_INST_top_DEF_m_randomC_initialized__h16860;
	 INST_top.DEF_WILL_FIRE_RL_m_maybe_clear = INST_top.DEF_CAN_FIRE_RL_m_maybe_clear;
	 DEF_INST_top_DEF_m_randomA_initialized__h16110 = INST_top.INST_m_randomA_initialized.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_randomA_every_1 = !DEF_INST_top_DEF_m_randomA_initialized__h16110;
	 INST_top.DEF_WILL_FIRE_RL_m_randomA_every_1 = INST_top.DEF_CAN_FIRE_RL_m_randomA_every_1;
	 INST_top.DEF_CAN_FIRE_RL_m_randomB_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_randomB_every = INST_top.DEF_CAN_FIRE_RL_m_randomB_every;
	 DEF_INST_top_DEF_m_randomB_initialized__h16486 = INST_top.INST_m_randomB_initialized.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_randomB_every_1 = !DEF_INST_top_DEF_m_randomB_initialized__h16486;
	 INST_top.DEF_WILL_FIRE_RL_m_randomB_every_1 = INST_top.DEF_CAN_FIRE_RL_m_randomB_every_1;
	 INST_top.DEF_CAN_FIRE_RL_m_randomC_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_randomC_every = INST_top.DEF_CAN_FIRE_RL_m_randomC_every;
	 INST_top.DEF_CAN_FIRE_RL_m_randomC_every_1 = !DEF_INST_top_DEF_m_randomC_initialized__h16860;
	 INST_top.DEF_WILL_FIRE_RL_m_randomC_every_1 = INST_top.DEF_CAN_FIRE_RL_m_randomC_every_1;
	 INST_top.DEF_CAN_FIRE_RL_m_randomData_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_randomData_every = INST_top.DEF_CAN_FIRE_RL_m_randomData_every;
	 DEF_INST_top_DEF_m_randomData_initialized__h17237 = INST_top.INST_m_randomData_initialized.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_m_randomData_every_1 = !DEF_INST_top_DEF_m_randomData_initialized__h17237;
	 INST_top.DEF_WILL_FIRE_RL_m_randomData_every_1 = INST_top.DEF_CAN_FIRE_RL_m_randomData_every_1;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_elem_count_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_elem_count_canonicalize = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_elem_count_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_enq_req_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_enq_req_canonicalize = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_enq_req_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_1 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_1 = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_1;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_2 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_2 = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_2;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_one = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_one = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_one;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_3 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_3 = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_3;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_4 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_4 = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_4;
	 DEF_INST_top_DEF_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo_i_n_ETC___d84 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo.METH_i_notEmpty();
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_two = DEF_INST_top_DEF_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo_i_n_ETC___d84;
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_two = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_two;
	 INST_top.DEF_x__h23804 = INST_top.INST_m_input_count.METH_read();
	 INST_top.DEF_m_input_count_24_EQ_1024___d333 = (INST_top.DEF_x__h23804) == 1024u;
	 INST_top.DEF_CAN_FIRE_RL_m_stop_tb = INST_top.DEF_m_input_count_24_EQ_1024___d333 || (INST_top.DEF_x__h23951) == 4096u;
	 INST_top.DEF_WILL_FIRE_RL_m_stop_tb = INST_top.DEF_CAN_FIRE_RL_m_stop_tb;
	 if (INST_top.DEF_WILL_FIRE_RL_m_cycle_print)
	   INST_top.RL_m_cycle_print();
	 if (INST_top.DEF_WILL_FIRE_RL_m_check_fifos_not_full)
	   INST_top.RL_m_check_fifos_not_full();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_one)
	   INST_top.RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_one();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_two)
	   INST_top.RL_m_ref_fifo_fake_bypass_fifo_pre_canonicalize_two();
	 if (INST_top.DEF_WILL_FIRE_RL_m_stop_tb)
	   INST_top.RL_m_stop_tb();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomA_every)
	   INST_top.RL_m_randomA_every();
	 INST_top.DEF_fifo_full_ehrReg__h4601 = INST_top.INST_fifo_full_ehrReg.METH_read();
	 INST_top.DEF_fifo_full_virtual_reg_0_read____d215 = INST_top.INST_fifo_full_virtual_reg_0.METH_read();
	 INST_top.DEF_fifo_full_virtual_reg_1_read____d214 = INST_top.INST_fifo_full_virtual_reg_1.METH_read();
	 INST_top.DEF_fifo_full_virtual_reg_2_read____d213 = INST_top.INST_fifo_full_virtual_reg_2.METH_read();
	 INST_top.DEF_fifo_full_virtual_reg_2_read__13_OR_fifo_full__ETC___d219 = INST_top.DEF_fifo_full_virtual_reg_2_read____d213 || (INST_top.DEF_fifo_full_virtual_reg_1_read____d214 || (INST_top.DEF_fifo_full_virtual_reg_0_read____d215 || !(INST_top.DEF_fifo_full_ehrReg__h4601)));
	 INST_top.DEF_def__h23403 = INST_top.INST_m_ref_fifo_elem_count_ehrReg.METH_read();
	 INST_top.DEF_x_wget__h15986 = INST_top.INST_m_randomA_zaz.METH_wget();
	 INST_top.DEF_m_ref_fifo_elem_count_virtual_reg_2_read____d205 = INST_top.INST_m_ref_fifo_elem_count_virtual_reg_2.METH_read();
	 INST_top.DEF_m_ref_fifo_elem_count_virtual_reg_1_read____d206 = INST_top.INST_m_ref_fifo_elem_count_virtual_reg_1.METH_read();
	 INST_top.DEF_n__read__h19790 = INST_top.DEF_m_ref_fifo_elem_count_virtual_reg_2_read____d205 || (INST_top.DEF_m_ref_fifo_elem_count_virtual_reg_1_read____d206 || INST_top.INST_m_ref_fifo_elem_count_virtual_reg_0.METH_read()) ? (tUInt8)0u : INST_top.DEF_def__h23403;
	 INST_top.DEF_v__h16116 = INST_top.INST_m_randomA_zaz.METH_whas() ? INST_top.DEF_x_wget__h15986 : (tUInt8)0u;
	 INST_top.DEF_IF_m_randomA_zaz_whas__78_THEN_m_randomA_zaz_w_ETC___d204 = (INST_top.DEF_v__h16116) == (tUInt8)0u;
	 INST_top.DEF_NOT_IF_m_ref_fifo_elem_count_virtual_reg_2_rea_ETC___d212 = !((INST_top.DEF_n__read__h19790) == (tUInt8)3u);
	 INST_top.DEF_CAN_FIRE_RL_m_feed_inputs = (DEF_INST_top_DEF_m_randomA_initialized__h16110 && (INST_top.DEF_IF_m_randomA_zaz_whas__78_THEN_m_randomA_zaz_w_ETC___d204 || (INST_top.DEF_NOT_IF_m_ref_fifo_elem_count_virtual_reg_2_rea_ETC___d212 && (INST_top.DEF_fifo_full_virtual_reg_2_read__13_OR_fifo_full__ETC___d219 && DEF_INST_top_DEF_m_randomData_initialized__h17237)))) && (INST_top.DEF_x__h23804) < 1024u;
	 INST_top.DEF_WILL_FIRE_RL_m_feed_inputs = INST_top.DEF_CAN_FIRE_RL_m_feed_inputs;
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomA_every_1)
	   INST_top.RL_m_randomA_every_1();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomB_every)
	   INST_top.RL_m_randomB_every();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomB_every_1)
	   INST_top.RL_m_randomB_every_1();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomC_every)
	   INST_top.RL_m_randomC_every();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomC_every_1)
	   INST_top.RL_m_randomC_every_1();
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomData_every)
	   INST_top.RL_m_randomData_every();
	 if (INST_top.DEF_WILL_FIRE_RL_m_feed_inputs)
	   INST_top.RL_m_feed_inputs();
	 INST_top.DEF_fifo_empty_virtual_reg_1_read____d259 = INST_top.INST_fifo_empty_virtual_reg_1.METH_read();
	 INST_top.DEF_fifo_empty_virtual_reg_2_read____d258 = INST_top.INST_fifo_empty_virtual_reg_2.METH_read();
	 INST_top.DEF_x_wget__h12540 = INST_top.INST_m_ref_fifo_elem_count_wires_0.METH_wget();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_read____d265 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4.METH_read();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_4_whas____d77 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_4.METH_whas();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_4_wget____d78 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_4.METH_wget();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_4__h9787 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg_4.METH_read();
	 INST_top.DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_4_whas__ETC___d80 = INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_4_whas____d77 ? INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_4_wget____d78 : INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_4__h9787;
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_re_ETC___d269 = INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_read____d265 || (INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_4_whas____d77 ? !(INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_4_wget____d78) : !(INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_4__h9787));
	 INST_top.DEF_fifo_empty_wires_0_whas____d25 = INST_top.INST_fifo_empty_wires_0.METH_whas();
	 INST_top.DEF_fifo_empty_wires_0_wget____d26 = INST_top.INST_fifo_empty_wires_0.METH_wget();
	 INST_top.DEF_fifo_empty_ehrReg__h3485 = INST_top.INST_fifo_empty_ehrReg.METH_read();
	 INST_top.DEF_IF_fifo_empty_wires_0_whas__5_THEN_fifo_empty__ETC___d28 = INST_top.DEF_fifo_empty_wires_0_whas____d25 ? INST_top.DEF_fifo_empty_wires_0_wget____d26 : INST_top.DEF_fifo_empty_ehrReg__h3485;
	 INST_top.DEF_def__h13340 = INST_top.INST_m_ref_fifo_elem_count_wires_0.METH_whas() ? INST_top.DEF_x_wget__h12540 : INST_top.DEF_def__h23403;
	 INST_top.DEF_n__read__h21435 = INST_top.DEF_m_ref_fifo_elem_count_virtual_reg_2_read____d205 || INST_top.DEF_m_ref_fifo_elem_count_virtual_reg_1_read____d206 ? (tUInt8)0u : INST_top.DEF_def__h13340;
	 INST_top.DEF_IF_m_ref_fifo_elem_count_virtual_reg_2_read__0_ETC___d256 = (INST_top.DEF_n__read__h21435) == (tUInt8)0u;
	 DEF_INST_top_DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_re_ETC___d270 = INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_re_ETC___d269 || INST_top.DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_4_whas__ETC___d80;
	 INST_top.DEF_NOT_fifo_empty_virtual_reg_2_read__58_22_AND_N_ETC___d325 = !(INST_top.DEF_fifo_empty_virtual_reg_2_read____d258) && (!(INST_top.DEF_fifo_empty_virtual_reg_1_read____d259) && INST_top.DEF_IF_fifo_empty_wires_0_whas__5_THEN_fifo_empty__ETC___d28);
	 INST_top.DEF_CAN_FIRE_RL_m_check_fifos_first = (INST_top.DEF_IF_m_ref_fifo_elem_count_virtual_reg_2_read__0_ETC___d256 || INST_top.DEF_NOT_fifo_empty_virtual_reg_2_read__58_22_AND_N_ETC___d325) || DEF_INST_top_DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_re_ETC___d270;
	 INST_top.DEF_WILL_FIRE_RL_m_check_fifos_first = INST_top.DEF_CAN_FIRE_RL_m_check_fifos_first && !(INST_top.DEF_WILL_FIRE_RL_m_feed_inputs);
	 INST_top.DEF_x_wget__h16362 = INST_top.INST_m_randomB_zaz.METH_wget();
	 INST_top.DEF_fifo_empty_virtual_reg_2_read__58_OR_fifo_empt_ETC___d264 = INST_top.DEF_fifo_empty_virtual_reg_2_read____d258 || (INST_top.DEF_fifo_empty_virtual_reg_1_read____d259 || (INST_top.DEF_fifo_empty_wires_0_whas____d25 ? !(INST_top.DEF_fifo_empty_wires_0_wget____d26) : !(INST_top.DEF_fifo_empty_ehrReg__h3485)));
	 INST_top.DEF_v__h16492 = INST_top.INST_m_randomB_zaz.METH_whas() ? INST_top.DEF_x_wget__h16362 : (tUInt8)0u;
	 INST_top.DEF_IF_m_randomB_zaz_whas__85_THEN_m_randomB_zaz_w_ETC___d253 = (INST_top.DEF_v__h16492) == (tUInt8)0u;
	 INST_top.DEF_NOT_IF_m_ref_fifo_elem_count_virtual_reg_2_rea_ETC___d257 = !(INST_top.DEF_IF_m_ref_fifo_elem_count_virtual_reg_2_read__0_ETC___d256);
	 INST_top.DEF_CAN_FIRE_RL_m_check_outputs = (DEF_INST_top_DEF_m_randomB_initialized__h16486 && (INST_top.DEF_IF_m_randomB_zaz_whas__85_THEN_m_randomB_zaz_w_ETC___d253 || (INST_top.DEF_NOT_IF_m_ref_fifo_elem_count_virtual_reg_2_rea_ETC___d257 && (INST_top.DEF_fifo_empty_virtual_reg_2_read__58_OR_fifo_empt_ETC___d264 && DEF_INST_top_DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_4_re_ETC___d270)))) && !(INST_top.DEF_CAN_FIRE_RL_m_randomB_every_1);
	 INST_top.DEF_WILL_FIRE_RL_m_check_outputs = INST_top.DEF_CAN_FIRE_RL_m_check_outputs && !(INST_top.DEF_WILL_FIRE_RL_m_feed_inputs);
	 if (INST_top.DEF_WILL_FIRE_RL_m_check_fifos_not_empty)
	   INST_top.RL_m_check_fifos_not_empty();
	 if (INST_top.DEF_WILL_FIRE_RL_m_check_fifos_first)
	   INST_top.RL_m_check_fifos_first();
	 if (INST_top.DEF_WILL_FIRE_RL_m_check_outputs)
	   INST_top.RL_m_check_outputs();
	 INST_top.DEF_m_ref_fifo_enq_req_virtual_reg_2_read____d147 = INST_top.INST_m_ref_fifo_enq_req_virtual_reg_2.METH_read();
	 INST_top.DEF_m_ref_fifo_enq_req_wires_1_wget____d140 = INST_top.INST_m_ref_fifo_enq_req_wires_1.METH_wget();
	 INST_top.DEF_m_ref_fifo_enq_req_wires_0_wget____d142 = INST_top.INST_m_ref_fifo_enq_req_wires_0.METH_wget();
	 INST_top.DEF_m_ref_fifo_enq_req_ehrReg___d143 = INST_top.INST_m_ref_fifo_enq_req_ehrReg.METH_read();
	 INST_top.DEF_m_ref_fifo_enq_req_wires_1_whas____d139 = INST_top.INST_m_ref_fifo_enq_req_wires_1.METH_whas();
	 INST_top.DEF_m_ref_fifo_enq_req_wires_0_whas____d141 = INST_top.INST_m_ref_fifo_enq_req_wires_0.METH_whas();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_3__h8958 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg_3.METH_read();
	 INST_top.DEF_m_ref_fifo_enq_req_ehrReg_43_BIT_8___d152 = (tUInt8)((INST_top.DEF_m_ref_fifo_enq_req_ehrReg___d143) >> 8u);
	 INST_top.DEF_m_ref_fifo_enq_req_wires_0_wget__42_BIT_8___d150 = (tUInt8)((INST_top.DEF_m_ref_fifo_enq_req_wires_0_wget____d142) >> 8u);
	 INST_top.DEF_m_ref_fifo_enq_req_wires_1_wget__40_BIT_8___d148 = (tUInt8)((INST_top.DEF_m_ref_fifo_enq_req_wires_1_wget____d140) >> 8u);
	 INST_top.DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_3_whas__ETC___d73 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_3.METH_whas() ? INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_3.METH_wget() : INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_3__h8958;
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize = (INST_top.DEF_m_ref_fifo_enq_req_virtual_reg_2_read____d147 || (INST_top.DEF_m_ref_fifo_enq_req_wires_1_whas____d139 ? !(INST_top.DEF_m_ref_fifo_enq_req_wires_1_wget__40_BIT_8___d148) : (INST_top.DEF_m_ref_fifo_enq_req_wires_0_whas____d141 ? !(INST_top.DEF_m_ref_fifo_enq_req_wires_0_wget__42_BIT_8___d150) : !(INST_top.DEF_m_ref_fifo_enq_req_ehrReg_43_BIT_8___d152)))) || (!INST_top.INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_3.METH_read() && INST_top.DEF_IF_m_ref_fifo_fake_bypass_fifo_wires_0_3_whas__ETC___d73);
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_canonicalize;
	 if (INST_top.DEF_WILL_FIRE_RL_m_randomData_every_1)
	   INST_top.RL_m_randomData_every_1();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_canonicalize)
	   INST_top.RL_m_ref_fifo_canonicalize();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_read____d87 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1.METH_read();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_2_read____d86 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_2.METH_read();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_wget____d46 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0.METH_wget();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_wget____d56 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_1.METH_wget();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg___d47 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg.METH_read();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_1___d57 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg_1.METH_read();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_2_1_read____d97 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_2_1.METH_read();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_1_read____d98 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_1.METH_read();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_whas____d55 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_1.METH_whas();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_whas____d45 = INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0.METH_whas();
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_wget__6_BIT_8___d88 = (tUInt8)((INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_wget____d46) >> 8u);
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_7_BIT_8___d90 = (tUInt8)((INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg___d47) >> 8u);
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_1_7_BIT_1___d101 = (tUInt8)((INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_1___d57) >> 1u);
	 INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_wget__6__ETC___d99 = (tUInt8)((INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_wget____d56) >> 1u);
	 INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_post_canonicalize = ((INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_2_read____d86 || (INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_read____d87 || (INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_whas____d45 ? !(INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_wget__6_BIT_8___d88) : !(INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_7_BIT_8___d90)))) || INST_top.INST_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo.METH_i_notFull()) && ((INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_2_1_read____d97 || (INST_top.DEF_m_ref_fifo_fake_bypass_fifo_virtual_reg_1_1_read____d98 || (INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_whas____d55 ? !(INST_top.DEF_m_ref_fifo_fake_bypass_fifo_wires_0_1_wget__6__ETC___d99) : !(INST_top.DEF_m_ref_fifo_fake_bypass_fifo_ehrReg_1_7_BIT_1___d101)))) || DEF_INST_top_DEF_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo_i_n_ETC___d84);
	 INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_post_canonicalize = INST_top.DEF_CAN_FIRE_RL_m_ref_fifo_fake_bypass_fifo_post_canonicalize;
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_enq_req_canonicalize)
	   INST_top.RL_m_ref_fifo_enq_req_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_2)
	   INST_top.RL_m_ref_fifo_fake_bypass_fifo_canonicalize_2();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_3)
	   INST_top.RL_m_ref_fifo_fake_bypass_fifo_canonicalize_3();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_4)
	   INST_top.RL_m_ref_fifo_fake_bypass_fifo_canonicalize_4();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_post_canonicalize)
	   INST_top.RL_m_ref_fifo_fake_bypass_fifo_post_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_m_maybe_clear)
	   INST_top.RL_m_maybe_clear();
	 if (INST_top.DEF_WILL_FIRE_RL_fifo_deqP_canonicalize)
	   INST_top.RL_fifo_deqP_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_fifo_empty_canonicalize)
	   INST_top.RL_fifo_empty_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_fifo_enqP_canonicalize)
	   INST_top.RL_fifo_enqP_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_fifo_full_canonicalize)
	   INST_top.RL_fifo_full_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_m_init)
	   INST_top.RL_m_init();
	 if (INST_top.DEF_WILL_FIRE_RL_m_cycle_inc)
	   INST_top.RL_m_cycle_inc();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_elem_count_canonicalize)
	   INST_top.RL_m_ref_fifo_elem_count_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize)
	   INST_top.RL_m_ref_fifo_fake_bypass_fifo_canonicalize();
	 if (INST_top.DEF_WILL_FIRE_RL_m_ref_fifo_fake_bypass_fifo_canonicalize_1)
	   INST_top.RL_m_ref_fifo_fake_bypass_fifo_canonicalize_1();
	 INST_top.INST_m_randomData_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomData_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomC_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomC_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomB_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomB_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomA_zaz.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_randomA_ignore.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_enq_req_ignored_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_enq_req_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_enq_req_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_enq_req_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_enq_req_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_enq_req_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_elem_count_ignored_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_elem_count_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_elem_count_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_elem_count_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_elem_count_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_elem_count_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_1_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_1_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_1_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_2_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_2_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_ref_fifo_fake_bypass_fifo_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_full_ignored_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_full_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_full_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_full_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_full_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_full_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_empty_ignored_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_empty_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_empty_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_empty_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_empty_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_empty_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqP_ignored_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqP_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqP_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqP_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqP_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_deqP_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqP_ignored_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqP_ignored_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqP_ignored_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqP_wires_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqP_wires_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fifo_enqP_wires_0.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_fifo_enqP_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_deqP_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_empty_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fifo_full_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_fake_bypass_fifo_ehrReg_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_elem_count_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_ref_fifo_enq_req_ehrReg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_cycle.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_input_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_output_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_randomA_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_randomB_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_randomC_initialized.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_randomData_initialized.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTbBypassFunctional::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTbBypassFunctional_instance = new MOD_mkTbBypassFunctional(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTbBypassFunctional_instance->INST_fifo_enqP_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_enqP_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_enqP_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_enqP_ignored_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_enqP_ignored_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_enqP_ignored_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_deqP_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_deqP_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_deqP_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_deqP_ignored_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_deqP_ignored_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_deqP_ignored_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_empty_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_empty_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_empty_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_empty_ignored_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_empty_ignored_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_empty_ignored_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_full_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_full_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_full_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_full_ignored_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_full_ignored_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_fifo_full_ignored_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ref_noncf_fifo.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_0_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_1_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_2_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_2_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_0_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_1_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_0_3.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_1_3.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_3.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_3.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_0_4.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_wires_1_4.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_0_4.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_fake_bypass_fifo_ignored_wires_1_4.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_elem_count_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_elem_count_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_elem_count_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_elem_count_ignored_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_elem_count_ignored_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_elem_count_ignored_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_enq_req_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_enq_req_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_enq_req_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_enq_req_ignored_wires_0.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_enq_req_ignored_wires_1.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_ref_fifo_enq_req_ignored_wires_2.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_randomA_ignore.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_randomA_zaz.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_randomB_ignore.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_randomB_zaz.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_randomC_ignore.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_randomC_zaz.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_randomData_ignore.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->INST_m_randomData_zaz.set_clk_0)("CLK");
  (mkTbBypassFunctional_instance->set_clk_0)("CLK");
}
void MODEL_mkTbBypassFunctional::destroy_model()
{
  delete mkTbBypassFunctional_instance;
  mkTbBypassFunctional_instance = NULL;
}
void MODEL_mkTbBypassFunctional::reset_model(bool asserted)
{
  (mkTbBypassFunctional_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTbBypassFunctional::get_instance()
{
  return mkTbBypassFunctional_instance;
}

/* Fill in version numbers */
void MODEL_mkTbBypassFunctional::get_version(char const **name, char const **build)
{
  *name = "2024.01-20-g9a97f9d0";
  *build = "9a97f9d0";
}

/* Get the model creation time */
time_t MODEL_mkTbBypassFunctional::get_creation_time()
{
  
  /* Thu Aug 15 12:41:06 UTC 2024 */
  return 1723725666llu;
}

/* State dumping function */
void MODEL_mkTbBypassFunctional::dump_state()
{
  (mkTbBypassFunctional_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTbBypassFunctional & mkTbBypassFunctional_backing(tSimStateHdl simHdl)
{
  static MOD_mkTbBypassFunctional *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTbBypassFunctional(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTbBypassFunctional::dump_VCD_defs()
{
  (mkTbBypassFunctional_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTbBypassFunctional::dump_VCD(tVCDDumpType dt)
{
  (mkTbBypassFunctional_instance->dump_VCD)(dt,
					    vcd_depth(sim_hdl),
					    mkTbBypassFunctional_backing(sim_hdl));
}
