/*
 * Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
 * 
 * On Thu Sep  5 19:31:07 CST 2024
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkPitchAdjustTest.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkPitchAdjustTest::MODEL_mkPitchAdjustTest()
{
  mkPitchAdjustTest_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkPitchAdjustTest()
{
  MODEL_mkPitchAdjustTest *model = new MODEL_mkPitchAdjustTest();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkPitchAdjustTest &INST_top = *((MOD_mkPitchAdjustTest *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_NOT_adjust_init_flag___d9;
	 tUInt8 DEF_INST_top_DEF_adjust_i_EQ_8___d3;
	 tUInt8 DEF_INST_top_DEF_adjust_inputFIFO_i_notFull____d133;
	 tUInt8 DEF_INST_top_DEF_adjust_outputFIFO_i_notEmpty____d142;
	 tUInt8 DEF_INST_top_DEF_adjust_init_flag__h3188;
	 INST_top.DEF_x__h8223 = INST_top.INST_adjust_i.METH_read();
	 DEF_INST_top_DEF_adjust_init_flag__h3188 = INST_top.INST_adjust_init_flag.METH_read();
	 DEF_INST_top_DEF_adjust_i_EQ_8___d3 = (INST_top.DEF_x__h8223) == (tUInt8)8u;
	 INST_top.DEF_CAN_FIRE_RL_adjust_inputRule = INST_top.INST_adjust_inputFIFO.METH_i_notEmpty() && (DEF_INST_top_DEF_adjust_i_EQ_8___d3 || DEF_INST_top_DEF_adjust_init_flag__h3188);
	 INST_top.DEF_WILL_FIRE_RL_adjust_inputRule = INST_top.DEF_CAN_FIRE_RL_adjust_inputRule;
	 DEF_INST_top_DEF_NOT_adjust_init_flag___d9 = !DEF_INST_top_DEF_adjust_init_flag__h3188;
	 INST_top.DEF_CAN_FIRE_RL_adjust_outputRule = INST_top.INST_adjust_outputFIFO.METH_i_notFull() && (DEF_INST_top_DEF_adjust_i_EQ_8___d3 && DEF_INST_top_DEF_NOT_adjust_init_flag___d9);
	 INST_top.DEF_WILL_FIRE_RL_adjust_outputRule = INST_top.DEF_CAN_FIRE_RL_adjust_outputRule;
	 INST_top.DEF_CAN_FIRE_RL_adjust_processDataRule = (INST_top.DEF_x__h8223) < (tUInt8)8u && DEF_INST_top_DEF_NOT_adjust_init_flag___d9;
	 INST_top.DEF_WILL_FIRE_RL_adjust_processDataRule = INST_top.DEF_CAN_FIRE_RL_adjust_processDataRule;
	 INST_top.DEF_x__h20861 = INST_top.INST_check.METH_read();
	 DEF_INST_top_DEF_adjust_outputFIFO_i_notEmpty____d142 = INST_top.INST_adjust_outputFIFO.METH_i_notEmpty();
	 INST_top.DEF_CAN_FIRE_RL_c0 = DEF_INST_top_DEF_adjust_outputFIFO_i_notEmpty____d142 && (INST_top.DEF_x__h20861) == 0u;
	 INST_top.DEF_WILL_FIRE_RL_c0 = INST_top.DEF_CAN_FIRE_RL_c0;
	 INST_top.DEF_CAN_FIRE_RL_c1 = DEF_INST_top_DEF_adjust_outputFIFO_i_notEmpty____d142 && (INST_top.DEF_x__h20861) == 1u;
	 INST_top.DEF_WILL_FIRE_RL_c1 = INST_top.DEF_CAN_FIRE_RL_c1;
	 INST_top.DEF_CAN_FIRE_RL_c2 = DEF_INST_top_DEF_adjust_outputFIFO_i_notEmpty____d142 && (INST_top.DEF_x__h20861) == 2u;
	 INST_top.DEF_WILL_FIRE_RL_c2 = INST_top.DEF_CAN_FIRE_RL_c2;
	 INST_top.DEF_x__h20856 = INST_top.INST_feed.METH_read();
	 DEF_INST_top_DEF_adjust_inputFIFO_i_notFull____d133 = INST_top.INST_adjust_inputFIFO.METH_i_notFull();
	 INST_top.DEF_CAN_FIRE_RL_f0 = DEF_INST_top_DEF_adjust_inputFIFO_i_notFull____d133 && (INST_top.DEF_x__h20856) == 0u;
	 INST_top.DEF_WILL_FIRE_RL_f0 = INST_top.DEF_CAN_FIRE_RL_f0;
	 INST_top.DEF_CAN_FIRE_RL_f1 = DEF_INST_top_DEF_adjust_inputFIFO_i_notFull____d133 && (INST_top.DEF_x__h20856) == 1u;
	 INST_top.DEF_WILL_FIRE_RL_f1 = INST_top.DEF_CAN_FIRE_RL_f1;
	 INST_top.DEF_CAN_FIRE_RL_f2 = DEF_INST_top_DEF_adjust_inputFIFO_i_notFull____d133 && (INST_top.DEF_x__h20856) == 2u;
	 INST_top.DEF_WILL_FIRE_RL_f2 = INST_top.DEF_CAN_FIRE_RL_f2;
	 INST_top.DEF_CAN_FIRE_RL_finish = (INST_top.DEF_x__h20856) == 3u && (INST_top.DEF_x__h20861) == 3u;
	 INST_top.DEF_WILL_FIRE_RL_finish = INST_top.DEF_CAN_FIRE_RL_finish;
	 if (INST_top.DEF_WILL_FIRE_RL_adjust_outputRule)
	   INST_top.RL_adjust_outputRule();
	 if (INST_top.DEF_WILL_FIRE_RL_adjust_inputRule)
	   INST_top.RL_adjust_inputRule();
	 if (INST_top.DEF_WILL_FIRE_RL_adjust_processDataRule)
	   INST_top.RL_adjust_processDataRule();
	 if (INST_top.DEF_WILL_FIRE_RL_c0)
	   INST_top.RL_c0();
	 if (INST_top.DEF_WILL_FIRE_RL_c1)
	   INST_top.RL_c1();
	 if (INST_top.DEF_WILL_FIRE_RL_c2)
	   INST_top.RL_c2();
	 if (INST_top.DEF_WILL_FIRE_RL_f0)
	   INST_top.RL_f0();
	 if (INST_top.DEF_WILL_FIRE_RL_f1)
	   INST_top.RL_f1();
	 if (INST_top.DEF_WILL_FIRE_RL_f2)
	   INST_top.RL_f2();
	 if (INST_top.DEF_WILL_FIRE_RL_finish)
	   INST_top.RL_finish();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_adjust_inputFIFO.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_adjust_outputFIFO.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_adjust_inputData.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_outputData.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_inphases_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_inphases_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_inphases_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_inphases_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_inphases_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_inphases_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_inphases_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_inphases_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_outphases_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_outphases_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_outphases_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_outphases_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_outphases_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_outphases_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_outphases_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_outphases_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_i.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_bin.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_adjust_init_flag.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_passed.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_feed.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_check.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkPitchAdjustTest::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkPitchAdjustTest_instance = new MOD_mkPitchAdjustTest(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkPitchAdjustTest_instance->INST_adjust_inputFIFO.set_clk_0)("CLK");
  (mkPitchAdjustTest_instance->INST_adjust_outputFIFO.set_clk_0)("CLK");
  (mkPitchAdjustTest_instance->set_clk_0)("CLK");
}
void MODEL_mkPitchAdjustTest::destroy_model()
{
  delete mkPitchAdjustTest_instance;
  mkPitchAdjustTest_instance = NULL;
}
void MODEL_mkPitchAdjustTest::reset_model(bool asserted)
{
  (mkPitchAdjustTest_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkPitchAdjustTest::get_instance()
{
  return mkPitchAdjustTest_instance;
}

/* Fill in version numbers */
void MODEL_mkPitchAdjustTest::get_version(char const **name, char const **build)
{
  *name = "2024.01";
  *build = "ae2a2fc6";
}

/* Get the model creation time */
time_t MODEL_mkPitchAdjustTest::get_creation_time()
{
  
  /* Thu Sep  5 11:31:07 UTC 2024 */
  return 1725535867llu;
}

/* State dumping function */
void MODEL_mkPitchAdjustTest::dump_state()
{
  (mkPitchAdjustTest_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkPitchAdjustTest & mkPitchAdjustTest_backing(tSimStateHdl simHdl)
{
  static MOD_mkPitchAdjustTest *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkPitchAdjustTest(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkPitchAdjustTest::dump_VCD_defs()
{
  (mkPitchAdjustTest_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkPitchAdjustTest::dump_VCD(tVCDDumpType dt)
{
  (mkPitchAdjustTest_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkPitchAdjustTest_backing(sim_hdl));
}
