/*
 * Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
 * 
 * On Mon Aug 19 09:53:54 CST 2024
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTestDriver.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTestDriver::MODEL_mkTestDriver()
{
  mkTestDriver_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTestDriver()
{
  MODEL_mkTestDriver *model = new MODEL_mkTestDriver();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTestDriver &INST_top = *((MOD_mkTestDriver *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_m_inited___d213;
	 tUInt8 DEF_INST_top_DEF_m_doneread__h30693;
	 tUInt32 DEF_INST_top_DEF_x__h31435;
	 DEF_INST_top_DEF_x__h31435 = INST_top.INST_m_outstanding.METH_value();
	 DEF_INST_top_DEF_m_doneread__h30693 = INST_top.INST_m_doneread.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_finish = DEF_INST_top_DEF_m_doneread__h30693 && DEF_INST_top_DEF_x__h31435 == 0u;
	 INST_top.DEF_WILL_FIRE_RL_finish = INST_top.DEF_CAN_FIRE_RL_finish;
	 DEF_INST_top_DEF_m_inited___d213 = INST_top.INST_m_inited.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_init = !DEF_INST_top_DEF_m_inited___d213;
	 INST_top.DEF_WILL_FIRE_RL_init = INST_top.DEF_CAN_FIRE_RL_init;
	 INST_top.DEF_CAN_FIRE_RL_pipeline_process = INST_top.INST_pipeline_infifo.METH_i_notEmpty() && INST_top.INST_pipeline_outfifo.METH_i_notFull();
	 INST_top.DEF_WILL_FIRE_RL_pipeline_process = INST_top.DEF_CAN_FIRE_RL_pipeline_process;
	 INST_top.DEF_CAN_FIRE_RL_read = INST_top.INST_pipeline_infifo.METH_i_notFull() && ((DEF_INST_top_DEF_m_inited___d213 && !DEF_INST_top_DEF_m_doneread__h30693) && !(DEF_INST_top_DEF_x__h31435 == 4294967295u));
	 INST_top.DEF_WILL_FIRE_RL_read = INST_top.DEF_CAN_FIRE_RL_read;
	 INST_top.DEF_CAN_FIRE_RL_write = INST_top.INST_pipeline_outfifo.METH_i_notEmpty() && DEF_INST_top_DEF_m_inited___d213;
	 INST_top.DEF_WILL_FIRE_RL_write = INST_top.DEF_CAN_FIRE_RL_write;
	 if (INST_top.DEF_WILL_FIRE_RL_finish)
	   INST_top.RL_finish();
	 if (INST_top.DEF_WILL_FIRE_RL_init)
	   INST_top.RL_init();
	 if (INST_top.DEF_WILL_FIRE_RL_pipeline_process)
	   INST_top.RL_pipeline_process();
	 if (INST_top.DEF_WILL_FIRE_RL_read)
	   INST_top.RL_read();
	 if (INST_top.DEF_WILL_FIRE_RL_write)
	   INST_top.RL_write();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_pipeline_multiplier.INST_results.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_pipeline_infifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_pipeline_outfifo.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_pipeline_r0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_pipeline_r1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_pipeline_r2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_pipeline_r3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_pipeline_r4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_pipeline_r5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_pipeline_r6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_pipeline_r7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_inited.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_doneread.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_outstanding.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTestDriver::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTestDriver_instance = new MOD_mkTestDriver(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTestDriver_instance->INST_pipeline_infifo.set_clk_0)("CLK");
  (mkTestDriver_instance->INST_pipeline_outfifo.set_clk_0)("CLK");
  (mkTestDriver_instance->INST_pipeline_multiplier.INST_results.set_clk_0)("CLK");
  (mkTestDriver_instance->INST_pipeline_multiplier.set_clk_0)("CLK");
  (mkTestDriver_instance->INST_m_outstanding.set_clk_0)("CLK");
  (mkTestDriver_instance->set_clk_0)("CLK");
}
void MODEL_mkTestDriver::destroy_model()
{
  delete mkTestDriver_instance;
  mkTestDriver_instance = NULL;
}
void MODEL_mkTestDriver::reset_model(bool asserted)
{
  (mkTestDriver_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTestDriver::get_instance()
{
  return mkTestDriver_instance;
}

/* Fill in version numbers */
void MODEL_mkTestDriver::get_version(char const **name, char const **build)
{
  *name = "2024.01";
  *build = "ae2a2fc6";
}

/* Get the model creation time */
time_t MODEL_mkTestDriver::get_creation_time()
{
  
  /* Mon Aug 19 01:53:54 UTC 2024 */
  return 1724032434llu;
}

/* State dumping function */
void MODEL_mkTestDriver::dump_state()
{
  (mkTestDriver_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTestDriver & mkTestDriver_backing(tSimStateHdl simHdl)
{
  static MOD_mkTestDriver *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTestDriver(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTestDriver::dump_VCD_defs()
{
  (mkTestDriver_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTestDriver::dump_VCD(tVCDDumpType dt)
{
  (mkTestDriver_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTestDriver_backing(sim_hdl));
}
