/*
 * Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
 * 
 * On Wed Jul 17 18:37:00 CST 2024
 * 
 */

/* Generation options: keep-fires */
#ifndef __model_mkTbSignedVsUnsigned_h__
#define __model_mkTbSignedVsUnsigned_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkTbSignedVsUnsigned.h"

/* Class declaration for a model of mkTbSignedVsUnsigned */
class MODEL_mkTbSignedVsUnsigned : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkTbSignedVsUnsigned *mkTbSignedVsUnsigned_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkTbSignedVsUnsigned();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(char const **name, char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkTbSignedVsUnsigned();
}

#endif /* ifndef __model_mkTbSignedVsUnsigned_h__ */
