/*
 * Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
 * 
 * On Tue Aug  6 16:07:32 CST 2024
 * 
 */

/* Generation options: */
#ifndef __mkFftElasticPipeline_h__
#define __mkFftElasticPipeline_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkBfly4.h"


/* Class declaration for the mkFftElasticPipeline module */
class MOD_mkFftElasticPipeline : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkBfly4 INST_bfly_0_0;
  MOD_mkBfly4 INST_bfly_0_1;
  MOD_mkBfly4 INST_bfly_0_10;
  MOD_mkBfly4 INST_bfly_0_11;
  MOD_mkBfly4 INST_bfly_0_12;
  MOD_mkBfly4 INST_bfly_0_13;
  MOD_mkBfly4 INST_bfly_0_14;
  MOD_mkBfly4 INST_bfly_0_15;
  MOD_mkBfly4 INST_bfly_0_2;
  MOD_mkBfly4 INST_bfly_0_3;
  MOD_mkBfly4 INST_bfly_0_4;
  MOD_mkBfly4 INST_bfly_0_5;
  MOD_mkBfly4 INST_bfly_0_6;
  MOD_mkBfly4 INST_bfly_0_7;
  MOD_mkBfly4 INST_bfly_0_8;
  MOD_mkBfly4 INST_bfly_0_9;
  MOD_mkBfly4 INST_bfly_1_0;
  MOD_mkBfly4 INST_bfly_1_1;
  MOD_mkBfly4 INST_bfly_1_10;
  MOD_mkBfly4 INST_bfly_1_11;
  MOD_mkBfly4 INST_bfly_1_12;
  MOD_mkBfly4 INST_bfly_1_13;
  MOD_mkBfly4 INST_bfly_1_14;
  MOD_mkBfly4 INST_bfly_1_15;
  MOD_mkBfly4 INST_bfly_1_2;
  MOD_mkBfly4 INST_bfly_1_3;
  MOD_mkBfly4 INST_bfly_1_4;
  MOD_mkBfly4 INST_bfly_1_5;
  MOD_mkBfly4 INST_bfly_1_6;
  MOD_mkBfly4 INST_bfly_1_7;
  MOD_mkBfly4 INST_bfly_1_8;
  MOD_mkBfly4 INST_bfly_1_9;
  MOD_mkBfly4 INST_bfly_2_0;
  MOD_mkBfly4 INST_bfly_2_1;
  MOD_mkBfly4 INST_bfly_2_10;
  MOD_mkBfly4 INST_bfly_2_11;
  MOD_mkBfly4 INST_bfly_2_12;
  MOD_mkBfly4 INST_bfly_2_13;
  MOD_mkBfly4 INST_bfly_2_14;
  MOD_mkBfly4 INST_bfly_2_15;
  MOD_mkBfly4 INST_bfly_2_2;
  MOD_mkBfly4 INST_bfly_2_3;
  MOD_mkBfly4 INST_bfly_2_4;
  MOD_mkBfly4 INST_bfly_2_5;
  MOD_mkBfly4 INST_bfly_2_6;
  MOD_mkBfly4 INST_bfly_2_7;
  MOD_mkBfly4 INST_bfly_2_8;
  MOD_mkBfly4 INST_bfly_2_9;
  MOD_Reg<tUWide> INST_fifo1_da_ehrReg;
  MOD_Wire<tUWide> INST_fifo1_da_ignored_wires_0;
  MOD_Wire<tUWide> INST_fifo1_da_ignored_wires_1;
  MOD_Reg<tUInt8> INST_fifo1_da_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo1_da_virtual_reg_1;
  MOD_Wire<tUWide> INST_fifo1_da_wires_0;
  MOD_Wire<tUWide> INST_fifo1_da_wires_1;
  MOD_Reg<tUWide> INST_fifo1_db_ehrReg;
  MOD_Wire<tUWide> INST_fifo1_db_ignored_wires_0;
  MOD_Wire<tUWide> INST_fifo1_db_ignored_wires_1;
  MOD_Reg<tUInt8> INST_fifo1_db_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo1_db_virtual_reg_1;
  MOD_Wire<tUWide> INST_fifo1_db_wires_0;
  MOD_Wire<tUWide> INST_fifo1_db_wires_1;
  MOD_Reg<tUInt8> INST_fifo1_va_ehrReg;
  MOD_Wire<tUInt8> INST_fifo1_va_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo1_va_ignored_wires_1;
  MOD_Reg<tUInt8> INST_fifo1_va_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo1_va_virtual_reg_1;
  MOD_Wire<tUInt8> INST_fifo1_va_wires_0;
  MOD_Wire<tUInt8> INST_fifo1_va_wires_1;
  MOD_Reg<tUInt8> INST_fifo1_vb_ehrReg;
  MOD_Wire<tUInt8> INST_fifo1_vb_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo1_vb_ignored_wires_1;
  MOD_Reg<tUInt8> INST_fifo1_vb_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo1_vb_virtual_reg_1;
  MOD_Wire<tUInt8> INST_fifo1_vb_wires_0;
  MOD_Wire<tUInt8> INST_fifo1_vb_wires_1;
  MOD_Reg<tUWide> INST_fifo2_da_ehrReg;
  MOD_Wire<tUWide> INST_fifo2_da_ignored_wires_0;
  MOD_Wire<tUWide> INST_fifo2_da_ignored_wires_1;
  MOD_Reg<tUInt8> INST_fifo2_da_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo2_da_virtual_reg_1;
  MOD_Wire<tUWide> INST_fifo2_da_wires_0;
  MOD_Wire<tUWide> INST_fifo2_da_wires_1;
  MOD_Reg<tUWide> INST_fifo2_db_ehrReg;
  MOD_Wire<tUWide> INST_fifo2_db_ignored_wires_0;
  MOD_Wire<tUWide> INST_fifo2_db_ignored_wires_1;
  MOD_Reg<tUInt8> INST_fifo2_db_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo2_db_virtual_reg_1;
  MOD_Wire<tUWide> INST_fifo2_db_wires_0;
  MOD_Wire<tUWide> INST_fifo2_db_wires_1;
  MOD_Reg<tUInt8> INST_fifo2_va_ehrReg;
  MOD_Wire<tUInt8> INST_fifo2_va_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo2_va_ignored_wires_1;
  MOD_Reg<tUInt8> INST_fifo2_va_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo2_va_virtual_reg_1;
  MOD_Wire<tUInt8> INST_fifo2_va_wires_0;
  MOD_Wire<tUInt8> INST_fifo2_va_wires_1;
  MOD_Reg<tUInt8> INST_fifo2_vb_ehrReg;
  MOD_Wire<tUInt8> INST_fifo2_vb_ignored_wires_0;
  MOD_Wire<tUInt8> INST_fifo2_vb_ignored_wires_1;
  MOD_Reg<tUInt8> INST_fifo2_vb_virtual_reg_0;
  MOD_Reg<tUInt8> INST_fifo2_vb_virtual_reg_1;
  MOD_Wire<tUInt8> INST_fifo2_vb_wires_0;
  MOD_Wire<tUInt8> INST_fifo2_vb_wires_1;
  MOD_Reg<tUWide> INST_inFifo_da_ehrReg;
  MOD_Wire<tUWide> INST_inFifo_da_ignored_wires_0;
  MOD_Wire<tUWide> INST_inFifo_da_ignored_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_da_virtual_reg_0;
  MOD_Reg<tUInt8> INST_inFifo_da_virtual_reg_1;
  MOD_Wire<tUWide> INST_inFifo_da_wires_0;
  MOD_Wire<tUWide> INST_inFifo_da_wires_1;
  MOD_Reg<tUWide> INST_inFifo_db_ehrReg;
  MOD_Wire<tUWide> INST_inFifo_db_ignored_wires_0;
  MOD_Wire<tUWide> INST_inFifo_db_ignored_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_db_virtual_reg_0;
  MOD_Reg<tUInt8> INST_inFifo_db_virtual_reg_1;
  MOD_Wire<tUWide> INST_inFifo_db_wires_0;
  MOD_Wire<tUWide> INST_inFifo_db_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_va_ehrReg;
  MOD_Wire<tUInt8> INST_inFifo_va_ignored_wires_0;
  MOD_Wire<tUInt8> INST_inFifo_va_ignored_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_va_virtual_reg_0;
  MOD_Reg<tUInt8> INST_inFifo_va_virtual_reg_1;
  MOD_Wire<tUInt8> INST_inFifo_va_wires_0;
  MOD_Wire<tUInt8> INST_inFifo_va_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_vb_ehrReg;
  MOD_Wire<tUInt8> INST_inFifo_vb_ignored_wires_0;
  MOD_Wire<tUInt8> INST_inFifo_vb_ignored_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_vb_virtual_reg_0;
  MOD_Reg<tUInt8> INST_inFifo_vb_virtual_reg_1;
  MOD_Wire<tUInt8> INST_inFifo_vb_wires_0;
  MOD_Wire<tUInt8> INST_inFifo_vb_wires_1;
  MOD_Reg<tUWide> INST_outFifo_da_ehrReg;
  MOD_Wire<tUWide> INST_outFifo_da_ignored_wires_0;
  MOD_Wire<tUWide> INST_outFifo_da_ignored_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_da_virtual_reg_0;
  MOD_Reg<tUInt8> INST_outFifo_da_virtual_reg_1;
  MOD_Wire<tUWide> INST_outFifo_da_wires_0;
  MOD_Wire<tUWide> INST_outFifo_da_wires_1;
  MOD_Reg<tUWide> INST_outFifo_db_ehrReg;
  MOD_Wire<tUWide> INST_outFifo_db_ignored_wires_0;
  MOD_Wire<tUWide> INST_outFifo_db_ignored_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_db_virtual_reg_0;
  MOD_Reg<tUInt8> INST_outFifo_db_virtual_reg_1;
  MOD_Wire<tUWide> INST_outFifo_db_wires_0;
  MOD_Wire<tUWide> INST_outFifo_db_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_va_ehrReg;
  MOD_Wire<tUInt8> INST_outFifo_va_ignored_wires_0;
  MOD_Wire<tUInt8> INST_outFifo_va_ignored_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_va_virtual_reg_0;
  MOD_Reg<tUInt8> INST_outFifo_va_virtual_reg_1;
  MOD_Wire<tUInt8> INST_outFifo_va_wires_0;
  MOD_Wire<tUInt8> INST_outFifo_va_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_vb_ehrReg;
  MOD_Wire<tUInt8> INST_outFifo_vb_ignored_wires_0;
  MOD_Wire<tUInt8> INST_outFifo_vb_ignored_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_vb_virtual_reg_0;
  MOD_Reg<tUInt8> INST_outFifo_vb_virtual_reg_1;
  MOD_Wire<tUInt8> INST_outFifo_vb_wires_0;
  MOD_Wire<tUInt8> INST_outFifo_vb_wires_1;
 
 /* Constructor */
 public:
  MOD_mkFftElasticPipeline(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_enq_in;
  tUWide PORT_deq;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_inFifo_vb_virtual_reg_1_read____d29;
  tUInt8 DEF_outFifo_va_virtual_reg_1_read____d71;
  tUInt8 DEF_outFifo_va_ehrReg__h119523;
  tUInt8 DEF_inFifo_vb_ehrReg__h64502;
 
 /* Local definitions */
 private:
  tUInt8 DEF_outFifo_vb_virtual_reg_1_read____d68;
  tUInt8 DEF_fifo2_vb_virtual_reg_1_read____d146;
  tUInt8 DEF_fifo1_vb_virtual_reg_1_read____d107;
  tUInt8 DEF_fifo2_va_virtual_reg_1_read____d149;
  tUInt8 DEF_fifo1_va_virtual_reg_1_read____d110;
  tUInt8 DEF_inFifo_va_virtual_reg_1_read____d32;
  tUWide DEF_fifo2_db_wires_1_wget____d133;
  tUWide DEF_fifo2_db_wires_0_wget____d135;
  tUWide DEF_fifo2_db_ehrReg__h315338;
  tUWide DEF_fifo2_da_wires_1_wget____d119;
  tUWide DEF_fifo2_da_wires_0_wget____d121;
  tUWide DEF_fifo2_da_ehrReg__h283084;
  tUWide DEF_fifo1_db_wires_1_wget____d94;
  tUWide DEF_fifo1_db_wires_0_wget____d96;
  tUWide DEF_fifo1_db_ehrReg__h228069;
  tUWide DEF_fifo1_da_wires_1_wget____d80;
  tUWide DEF_fifo1_da_wires_0_wget____d82;
  tUWide DEF_fifo1_da_ehrReg__h195815;
  tUWide DEF_outFifo_db_wires_1_wget____d55;
  tUWide DEF_outFifo_db_wires_0_wget____d57;
  tUWide DEF_outFifo_db_ehrReg__h140800;
  tUWide DEF_outFifo_da_wires_1_wget____d41;
  tUWide DEF_outFifo_da_wires_0_wget____d43;
  tUWide DEF_outFifo_da_ehrReg__h108546;
  tUWide DEF_inFifo_db_wires_1_wget____d16;
  tUWide DEF_inFifo_db_wires_0_wget____d18;
  tUWide DEF_inFifo_db_ehrReg__h53525;
  tUWide DEF_inFifo_da_wires_1_wget____d2;
  tUWide DEF_inFifo_da_wires_0_wget____d4;
  tUWide DEF_inFifo_da_ehrReg__h21271;
  tUInt8 DEF_fifo2_vb_ehrReg__h326315;
  tUInt8 DEF_fifo2_va_wires_0_whas____d127;
  tUInt8 DEF_fifo2_va_wires_0_wget____d128;
  tUInt8 DEF_fifo2_va_ehrReg__h294061;
  tUInt8 DEF_fifo1_vb_ehrReg__h239046;
  tUInt8 DEF_fifo1_va_wires_0_whas____d88;
  tUInt8 DEF_fifo1_va_wires_0_wget____d89;
  tUInt8 DEF_fifo1_va_ehrReg__h206792;
  tUInt8 DEF_outFifo_vb_ehrReg__h151777;
  tUInt8 DEF_outFifo_va_wires_0_whas____d49;
  tUInt8 DEF_outFifo_va_wires_0_wget____d50;
  tUInt8 DEF_inFifo_va_wires_0_whas____d10;
  tUInt8 DEF_inFifo_va_wires_0_wget____d11;
  tUInt8 DEF_inFifo_va_ehrReg__h32248;
  tUWide DEF_IF_fifo2_db_virtual_reg_1_read__55_THEN_0_ELSE_ETC___d156;
  tUWide DEF_IF_fifo2_db_wires_0_whas__34_THEN_fifo2_db_wir_ETC___d137;
  tUWide DEF_IF_fifo2_db_wires_1_whas__32_THEN_fifo2_db_wir_ETC___d138;
  tUWide DEF_IF_fifo2_da_wires_1_whas__18_THEN_fifo2_da_wir_ETC___d124;
  tUWide DEF_IF_fifo2_da_wires_0_whas__20_THEN_fifo2_da_wir_ETC___d123;
  tUWide DEF_IF_fifo1_db_virtual_reg_1_read__16_THEN_0_ELSE_ETC___d117;
  tUWide DEF_IF_fifo1_db_wires_0_whas__5_THEN_fifo1_db_wire_ETC___d98;
  tUWide DEF_IF_fifo1_db_wires_1_whas__3_THEN_fifo1_db_wire_ETC___d99;
  tUWide DEF_IF_fifo1_da_wires_1_whas__9_THEN_fifo1_da_wire_ETC___d85;
  tUWide DEF_IF_fifo1_da_wires_0_whas__1_THEN_fifo1_da_wire_ETC___d84;
  tUWide DEF_IF_outFifo_db_virtual_reg_1_read__7_THEN_0_ELS_ETC___d78;
  tUWide DEF_IF_outFifo_db_wires_0_whas__6_THEN_outFifo_db__ETC___d59;
  tUWide DEF_IF_outFifo_db_wires_1_whas__4_THEN_outFifo_db__ETC___d60;
  tUWide DEF_IF_outFifo_da_wires_1_whas__0_THEN_outFifo_da__ETC___d46;
  tUWide DEF_IF_outFifo_da_wires_0_whas__2_THEN_outFifo_da__ETC___d45;
  tUWide DEF_IF_inFifo_db_virtual_reg_1_read__8_THEN_0_ELSE_ETC___d39;
  tUWide DEF_IF_inFifo_db_wires_0_whas__7_THEN_inFifo_db_wi_ETC___d20;
  tUWide DEF_IF_inFifo_db_wires_1_whas__5_THEN_inFifo_db_wi_ETC___d21;
  tUWide DEF_IF_inFifo_da_wires_0_whas_THEN_inFifo_da_wires_ETC___d6;
  tUWide DEF_IF_inFifo_da_wires_1_whas_THEN_inFifo_da_wires_ETC___d7;
  tUInt8 DEF_IF_fifo2_vb_wires_0_whas__41_THEN_fifo2_vb_wir_ETC___d144;
  tUInt8 DEF_IF_fifo2_va_wires_0_whas__27_THEN_fifo2_va_wir_ETC___d130;
  tUInt8 DEF_IF_fifo1_vb_wires_0_whas__02_THEN_fifo1_vb_wir_ETC___d105;
  tUInt8 DEF_IF_fifo1_va_wires_0_whas__8_THEN_fifo1_va_wire_ETC___d91;
  tUInt8 DEF_IF_outFifo_vb_wires_0_whas__3_THEN_outFifo_vb__ETC___d66;
  tUInt8 DEF_IF_outFifo_va_wires_0_whas__9_THEN_outFifo_va__ETC___d52;
  tUInt8 DEF_IF_inFifo_vb_wires_0_whas__4_THEN_inFifo_vb_wi_ETC___d27;
  tUInt8 DEF_IF_inFifo_va_wires_0_whas__0_THEN_inFifo_va_wi_ETC___d13;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d627;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d624;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d313;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d310;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d470;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d467;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d621;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d307;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d464;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d618;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d304;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d461;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d615;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d301;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d458;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d612;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d298;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d455;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d609;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d295;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d452;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d606;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d292;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d449;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d603;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d289;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d446;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d600;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d286;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d443;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d597;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d283;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d440;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d594;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d280;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d437;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d591;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d277;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d434;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d588;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d274;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d431;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d585;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d271;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d428;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d582;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d268;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d425;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d579;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d265;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d422;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d573;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d259;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d416;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d567;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d253;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d410;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d561;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d247;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d404;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d555;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d398;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d241;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d549;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d235;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d392;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d543;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d229;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d386;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d537;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d223;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d380;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d531;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d217;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d374;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d525;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d211;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d368;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d519;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d205;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d362;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d513;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d199;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d356;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d507;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d350;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d193;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_fifo2_d_ETC___d501;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_IF_inFifo__ETC___d187;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_fifo1_d_ETC___d344;
 
 /* Rules */
 public:
  void RL_inFifo_da_canonicalize();
  void RL_inFifo_va_canonicalize();
  void RL_inFifo_db_canonicalize();
  void RL_inFifo_vb_canonicalize();
  void RL_inFifo_canonicalize();
  void RL_outFifo_da_canonicalize();
  void RL_outFifo_va_canonicalize();
  void RL_outFifo_db_canonicalize();
  void RL_outFifo_vb_canonicalize();
  void RL_outFifo_canonicalize();
  void RL_fifo1_da_canonicalize();
  void RL_fifo1_va_canonicalize();
  void RL_fifo1_db_canonicalize();
  void RL_fifo1_vb_canonicalize();
  void RL_fifo1_canonicalize();
  void RL_fifo2_da_canonicalize();
  void RL_fifo2_va_canonicalize();
  void RL_fifo2_db_canonicalize();
  void RL_fifo2_vb_canonicalize();
  void RL_fifo2_canonicalize();
  void RL_stage0();
  void RL_stage1();
  void RL_stage2();
 
 /* Methods */
 public:
  void METH_enq(tUWide ARG_enq_in);
  tUInt8 METH_RDY_enq();
  tUWide METH_deq();
  tUInt8 METH_RDY_deq();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkFftElasticPipeline &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkFftElasticPipeline &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkFftElasticPipeline &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkFftElasticPipeline &backing);
};

#endif /* ifndef __mkFftElasticPipeline_h__ */
