/*
 * Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
 * 
 * On Tue Aug  6 16:07:32 CST 2024
 * 
 */

/* Generation options: */
#ifndef __mkFftCombinational_h__
#define __mkFftCombinational_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkBfly4.h"


/* Class declaration for the mkFftCombinational module */
class MOD_mkFftCombinational : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkBfly4 INST_bfly_0_0;
  MOD_mkBfly4 INST_bfly_0_1;
  MOD_mkBfly4 INST_bfly_0_10;
  MOD_mkBfly4 INST_bfly_0_11;
  MOD_mkBfly4 INST_bfly_0_12;
  MOD_mkBfly4 INST_bfly_0_13;
  MOD_mkBfly4 INST_bfly_0_14;
  MOD_mkBfly4 INST_bfly_0_15;
  MOD_mkBfly4 INST_bfly_0_2;
  MOD_mkBfly4 INST_bfly_0_3;
  MOD_mkBfly4 INST_bfly_0_4;
  MOD_mkBfly4 INST_bfly_0_5;
  MOD_mkBfly4 INST_bfly_0_6;
  MOD_mkBfly4 INST_bfly_0_7;
  MOD_mkBfly4 INST_bfly_0_8;
  MOD_mkBfly4 INST_bfly_0_9;
  MOD_mkBfly4 INST_bfly_1_0;
  MOD_mkBfly4 INST_bfly_1_1;
  MOD_mkBfly4 INST_bfly_1_10;
  MOD_mkBfly4 INST_bfly_1_11;
  MOD_mkBfly4 INST_bfly_1_12;
  MOD_mkBfly4 INST_bfly_1_13;
  MOD_mkBfly4 INST_bfly_1_14;
  MOD_mkBfly4 INST_bfly_1_15;
  MOD_mkBfly4 INST_bfly_1_2;
  MOD_mkBfly4 INST_bfly_1_3;
  MOD_mkBfly4 INST_bfly_1_4;
  MOD_mkBfly4 INST_bfly_1_5;
  MOD_mkBfly4 INST_bfly_1_6;
  MOD_mkBfly4 INST_bfly_1_7;
  MOD_mkBfly4 INST_bfly_1_8;
  MOD_mkBfly4 INST_bfly_1_9;
  MOD_mkBfly4 INST_bfly_2_0;
  MOD_mkBfly4 INST_bfly_2_1;
  MOD_mkBfly4 INST_bfly_2_10;
  MOD_mkBfly4 INST_bfly_2_11;
  MOD_mkBfly4 INST_bfly_2_12;
  MOD_mkBfly4 INST_bfly_2_13;
  MOD_mkBfly4 INST_bfly_2_14;
  MOD_mkBfly4 INST_bfly_2_15;
  MOD_mkBfly4 INST_bfly_2_2;
  MOD_mkBfly4 INST_bfly_2_3;
  MOD_mkBfly4 INST_bfly_2_4;
  MOD_mkBfly4 INST_bfly_2_5;
  MOD_mkBfly4 INST_bfly_2_6;
  MOD_mkBfly4 INST_bfly_2_7;
  MOD_mkBfly4 INST_bfly_2_8;
  MOD_mkBfly4 INST_bfly_2_9;
  MOD_Reg<tUWide> INST_inFifo_da_ehrReg;
  MOD_Wire<tUWide> INST_inFifo_da_ignored_wires_0;
  MOD_Wire<tUWide> INST_inFifo_da_ignored_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_da_virtual_reg_0;
  MOD_Reg<tUInt8> INST_inFifo_da_virtual_reg_1;
  MOD_Wire<tUWide> INST_inFifo_da_wires_0;
  MOD_Wire<tUWide> INST_inFifo_da_wires_1;
  MOD_Reg<tUWide> INST_inFifo_db_ehrReg;
  MOD_Wire<tUWide> INST_inFifo_db_ignored_wires_0;
  MOD_Wire<tUWide> INST_inFifo_db_ignored_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_db_virtual_reg_0;
  MOD_Reg<tUInt8> INST_inFifo_db_virtual_reg_1;
  MOD_Wire<tUWide> INST_inFifo_db_wires_0;
  MOD_Wire<tUWide> INST_inFifo_db_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_va_ehrReg;
  MOD_Wire<tUInt8> INST_inFifo_va_ignored_wires_0;
  MOD_Wire<tUInt8> INST_inFifo_va_ignored_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_va_virtual_reg_0;
  MOD_Reg<tUInt8> INST_inFifo_va_virtual_reg_1;
  MOD_Wire<tUInt8> INST_inFifo_va_wires_0;
  MOD_Wire<tUInt8> INST_inFifo_va_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_vb_ehrReg;
  MOD_Wire<tUInt8> INST_inFifo_vb_ignored_wires_0;
  MOD_Wire<tUInt8> INST_inFifo_vb_ignored_wires_1;
  MOD_Reg<tUInt8> INST_inFifo_vb_virtual_reg_0;
  MOD_Reg<tUInt8> INST_inFifo_vb_virtual_reg_1;
  MOD_Wire<tUInt8> INST_inFifo_vb_wires_0;
  MOD_Wire<tUInt8> INST_inFifo_vb_wires_1;
  MOD_Reg<tUWide> INST_outFifo_da_ehrReg;
  MOD_Wire<tUWide> INST_outFifo_da_ignored_wires_0;
  MOD_Wire<tUWide> INST_outFifo_da_ignored_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_da_virtual_reg_0;
  MOD_Reg<tUInt8> INST_outFifo_da_virtual_reg_1;
  MOD_Wire<tUWide> INST_outFifo_da_wires_0;
  MOD_Wire<tUWide> INST_outFifo_da_wires_1;
  MOD_Reg<tUWide> INST_outFifo_db_ehrReg;
  MOD_Wire<tUWide> INST_outFifo_db_ignored_wires_0;
  MOD_Wire<tUWide> INST_outFifo_db_ignored_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_db_virtual_reg_0;
  MOD_Reg<tUInt8> INST_outFifo_db_virtual_reg_1;
  MOD_Wire<tUWide> INST_outFifo_db_wires_0;
  MOD_Wire<tUWide> INST_outFifo_db_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_va_ehrReg;
  MOD_Wire<tUInt8> INST_outFifo_va_ignored_wires_0;
  MOD_Wire<tUInt8> INST_outFifo_va_ignored_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_va_virtual_reg_0;
  MOD_Reg<tUInt8> INST_outFifo_va_virtual_reg_1;
  MOD_Wire<tUInt8> INST_outFifo_va_wires_0;
  MOD_Wire<tUInt8> INST_outFifo_va_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_vb_ehrReg;
  MOD_Wire<tUInt8> INST_outFifo_vb_ignored_wires_0;
  MOD_Wire<tUInt8> INST_outFifo_vb_ignored_wires_1;
  MOD_Reg<tUInt8> INST_outFifo_vb_virtual_reg_0;
  MOD_Reg<tUInt8> INST_outFifo_vb_virtual_reg_1;
  MOD_Wire<tUInt8> INST_outFifo_vb_wires_0;
  MOD_Wire<tUInt8> INST_outFifo_vb_wires_1;
 
 /* Constructor */
 public:
  MOD_mkFftCombinational(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_enq_in;
  tUWide PORT_deq;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_inFifo_vb_virtual_reg_1_read____d29;
  tUInt8 DEF_outFifo_va_virtual_reg_1_read____d71;
  tUInt8 DEF_outFifo_va_ehrReg__h119522;
  tUInt8 DEF_inFifo_vb_ehrReg__h64501;
 
 /* Local definitions */
 private:
  tUInt8 DEF_outFifo_vb_virtual_reg_1_read____d68;
  tUInt8 DEF_inFifo_va_virtual_reg_1_read____d32;
  tUWide DEF_outFifo_db_wires_1_wget____d55;
  tUWide DEF_outFifo_db_wires_0_wget____d57;
  tUWide DEF_outFifo_da_wires_1_wget____d41;
  tUWide DEF_outFifo_da_wires_0_wget____d43;
  tUWide DEF_inFifo_db_wires_1_wget____d16;
  tUWide DEF_inFifo_db_wires_0_wget____d18;
  tUWide DEF_inFifo_da_wires_1_wget____d2;
  tUWide DEF_inFifo_da_wires_0_wget____d4;
  tUInt8 DEF_outFifo_va_wires_0_whas____d49;
  tUInt8 DEF_outFifo_va_wires_0_wget____d50;
  tUInt8 DEF_inFifo_va_wires_0_whas____d10;
  tUInt8 DEF_inFifo_va_wires_0_wget____d11;
  tUWide DEF_IF_outFifo_db_virtual_reg_1_read__7_THEN_0_ELS_ETC___d78;
  tUWide DEF_IF_outFifo_db_wires_0_whas__6_THEN_outFifo_db__ETC___d59;
  tUWide DEF_IF_outFifo_db_wires_1_whas__4_THEN_outFifo_db__ETC___d60;
  tUWide DEF_IF_outFifo_da_wires_1_whas__0_THEN_outFifo_da__ETC___d46;
  tUWide DEF_IF_outFifo_da_wires_0_whas__2_THEN_outFifo_da__ETC___d45;
  tUWide DEF_IF_inFifo_db_virtual_reg_1_read__8_THEN_0_ELSE_ETC___d39;
  tUWide DEF_IF_inFifo_db_wires_0_whas__7_THEN_inFifo_db_wi_ETC___d20;
  tUWide DEF_IF_inFifo_db_wires_1_whas__5_THEN_inFifo_db_wi_ETC___d21;
  tUWide DEF_IF_inFifo_da_wires_0_whas_THEN_inFifo_da_wires_ETC___d6;
  tUWide DEF_IF_inFifo_da_wires_1_whas_THEN_inFifo_da_wires_ETC___d7;
  tUInt8 DEF_IF_outFifo_vb_wires_0_whas__3_THEN_outFifo_vb__ETC___d66;
  tUInt8 DEF_IF_outFifo_va_wires_0_whas__9_THEN_outFifo_va__ETC___d52;
  tUInt8 DEF_IF_inFifo_vb_wires_0_whas__4_THEN_inFifo_vb_wi_ETC___d27;
  tUInt8 DEF_IF_inFifo_va_wires_0_whas__0_THEN_inFifo_va_wi_ETC___d13;
  tUWide DEF_outFifo_db_ehrReg__h140799;
  tUWide DEF_outFifo_da_ehrReg__h108545;
  tUWide DEF_inFifo_db_ehrReg__h53524;
  tUWide DEF_inFifo_da_ehrReg__h21270;
  tUInt8 DEF_outFifo_vb_ehrReg__h151776;
  tUInt8 DEF_inFifo_va_ehrReg__h32247;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d459;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d456;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d453;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d450;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d447;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d444;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d441;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d438;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d435;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d432;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d429;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d426;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d423;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d420;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d417;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d414;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d411;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d401;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d391;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d381;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d371;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d361;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d351;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d341;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d331;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d307;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d283;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d259;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d235;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d199;
 
 /* Rules */
 public:
  void RL_inFifo_da_canonicalize();
  void RL_inFifo_va_canonicalize();
  void RL_inFifo_db_canonicalize();
  void RL_inFifo_vb_canonicalize();
  void RL_inFifo_canonicalize();
  void RL_outFifo_da_canonicalize();
  void RL_outFifo_va_canonicalize();
  void RL_outFifo_db_canonicalize();
  void RL_outFifo_vb_canonicalize();
  void RL_outFifo_canonicalize();
  void RL_doFft();
 
 /* Methods */
 public:
  void METH_enq(tUWide ARG_enq_in);
  tUInt8 METH_RDY_enq();
  tUWide METH_deq();
  tUInt8 METH_RDY_deq();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkFftCombinational &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkFftCombinational &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkFftCombinational &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkFftCombinational &backing);
};

#endif /* ifndef __mkFftCombinational_h__ */
