/*
 * Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
 * 
 * On Mon Aug  5 08:26:03 CST 2024
 * 
 */

/* Generation options: */
#ifndef __model_mkTbFftInelasticPipeline_h__
#define __model_mkTbFftInelasticPipeline_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkTbFftInelasticPipeline.h"

/* Class declaration for a model of mkTbFftInelasticPipeline */
class MODEL_mkTbFftInelasticPipeline : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkTbFftInelasticPipeline *mkTbFftInelasticPipeline_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkTbFftInelasticPipeline();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(char const **name, char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkTbFftInelasticPipeline();
}

#endif /* ifndef __model_mkTbFftInelasticPipeline_h__ */
